import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const migrations=read('supabase/migrations/20261009003000_seo_center_phase1.sql')
const worker=read('worker/pwa.js')
const seoWorker=read('worker/seo.js')
const routes=read('src/AppV2.tsx')
const nav=read('src/layouts/AdminLayout.tsx')
const center=read('src/pages/admin/AdminSeo.tsx')
const client=read('src/components/RouteSeo.tsx')
const wrangler=read('wrangler.jsonc')

test('SEO tables are protected with separate public published read and staff write permissions',()=>{
 assert.match(migrations,/alter table public\.seo_pages enable row level security/)
 assert.match(migrations,/alter table public\.seo_keywords enable row level security/)
 assert.match(migrations,/seo_pages_admin_update/)
 assert.match(migrations,/current_user_has_permission\('site\.manage'\)/)
 assert.match(migrations,/seo_pages_public_read/)
 assert.match(migrations,/published or \(select public\.current_user_is_admin\(\)\)/)
 assert.match(migrations,/on conflict\(path\) do nothing/)
})
test('the editable SEO panel is reachable and discoverable under site management',()=>{
 assert.match(routes,/path="seo" element=\{<AdminPermissionGate permission="site\.manage">/)
 assert.match(nav,/href:'\/admin\/seo'/)
 assert.match(center,/Central de SEO/)
 assert.match(center,/seo_pages/)
 assert.match(center,/seo_keywords/)
 assert.match(center,/Salvar SEO da página/)
 assert.match(center,/Google Search Console: verificação/)
 assert.match(center,/GA4: vinculação/)
})
test('Cloudflare generates sitemap and robots from published indexable known routes',()=>{
 assert.match(wrangler,/"run_worker_first": \[/)
 assert.match(wrangler,/"\\/sitemap\\.xml"/)
 assert.match(wrangler,/"\\/robots\\.txt"/)
 assert.match(wrangler,/"\\/admin\\/\\*"/)
 assert.match(worker,/serveSeoSitemap\(request\)/)
 assert.match(worker,/serveSeoRobots\(request\)/)
 assert.match(seoWorker,/published=eq\.true&noindex=eq\.false/)
 assert.match(seoWorker,/PUBLIC_SEO_ROUTES\.has\(p\.path\)/)
 assert.match(seoWorker,/Disallow: \/admin\//)
 assert.match(seoWorker,/Sitemap: /)
})
test('initial HTML receives all major search meta signals with private pages noindexed',()=>{
 assert.match(seoWorker,/new HTMLRewriter\(\)/)
 assert.match(seoWorker,/meta name="description"/)
 assert.match(seoWorker,/rel="canonical"/)
 assert.match(seoWorker,/property="og:title"/)
 assert.match(seoWorker,/application\/ld\+json/)
 assert.match(worker,/isPrivateSeoRoute\(path\)/)
 assert.match(worker,/preventIndexing\(response\)/)
 assert.match(seoWorker,/if\(!PUBLIC_SEO_ROUTES\.has\(path\)\)return null/)
 assert.match(client,/from\('seo_pages'\)/)
})
