import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { academyApi } from '../../api/academy'
import { LoadingState,ErrorState } from '../../components/ui/AsyncState'
import { CompactPageHeader } from '../../components/ui/CompactWorkspace'

function courseStats(data:any){
 const lessons=data?.modules?.flatMap((m:any)=>m.lessons||[])||[]
 const completed=new Set((data?.progress||[]).filter((p:any)=>p.completed).map((p:any)=>p.lesson_id))
 const done=lessons.filter((l:any)=>completed.has(l.id)).length
 const last=[...(data?.progress||[])].filter((p:any)=>p.last_watched_at).sort((a:any,b:any)=>String(b.last_watched_at).localeCompare(String(a.last_watched_at)))[0]
 const moduleDone=(m:any)=>(m.lessons||[]).length>0&&(m.lessons||[]).every((l:any)=>completed.has(l.id))
 const modulesDone=(data?.modules||[]).filter(moduleDone).length
 return {total:lessons.length,done,percent:lessons.length?Math.round(done/lessons.length*100):0,modules:data?.modules?.length||0,modulesDone,lastAt:last?.last_watched_at||null}
}

export function AcademyPage(){
 const [rows,setRows]=useState<any[]>([]);const [documents,setDocuments]=useState<any[]>([]);const [docBusy,setDocBusy]=useState('');const [free,setFree]=useState<any[]>([]);const [stats,setStats]=useState<Record<string,any>>({});const [certificates,setCertificates]=useState<any[]>([]);const [academic,setAcademic]=useState<any>(null);const [record,setRecord]=useState<any>(null);const [recordBusy,setRecordBusy]=useState('');const [certBusy,setCertBusy]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 const load=()=>{setError('');setLoading(true);return Promise.all([academyApi.myCourses(),academyApi.freeCourses(),academyApi.myCertificates().catch(()=>[]),academyApi.myAcademicProfile().catch(()=>null),academyApi.myAcademicDocuments().catch(()=>[])]).then(async([mine,available,certs,academicProfile,docs])=>{setCertificates(certs);setAcademic(academicProfile);setDocuments(docs);const valid=mine.filter((r:any)=>r?.course);setRows(valid);const ids=new Set(valid.map((r:any)=>r.course_id));setFree(available.filter((c:any)=>c?.id&&!ids.has(c.id)));const pairs=await Promise.all(valid.map(async(r:any)=>{try{const refreshed=await academyApi.refreshEnrollment(r.id);const detail=await academyApi.courseForStudent(r.course_id);return [r.course_id,{...courseStats(detail),percent:Number(refreshed.progress_percent??0),status:refreshed.status,finalGrade:refreshed.final_grade,completedAt:refreshed.completed_at}] as const}catch{return [r.course_id,{total:0,done:0,percent:Number(r.progress_percent??0),modules:0,status:r.status,finalGrade:r.final_grade,completedAt:r.completed_at}] as const}}));setStats(Object.fromEntries(pairs))}).catch((e:any)=>setError(e.message||'Não foi possível carregar a Academia.')).finally(()=>setLoading(false))};useEffect(()=>{void load()},[])
 const acceptDocument=async(d:any)=>{try{setDocBusy(d.id);await academyApi.acceptAcademicDocument(d.id);setDocuments(await academyApi.myAcademicDocuments())}catch(e:any){setError(e.message||'Não foi possível registrar o aceite.')}finally{setDocBusy('')}}
 const continueRow=[...rows].filter((r:any)=>(stats[r.course_id]?.status||r.status)!=='completed').sort((a:any,b:any)=>String(stats[b.course_id]?.lastAt||b.enrolled_at||'').localeCompare(String(stats[a.course_id]?.lastAt||a.enrolled_at||'')))[0]
 const certificateFor=(courseId:string)=>certificates.find((item:any)=>item.course_id===courseId)
 const pendingDocuments=documents.filter((d:any)=>['contract','term'].includes(d.document_type)&&d.status!=='signed').length
 const completedCourses=rows.filter((r:any)=>(stats[r.course_id]?.status||r.status)==='completed').length
 const openRecord=async(e:any)=>{try{setRecordBusy(e.id);const fresh=await academyApi.refreshEnrollment(e.id);const detail=await academyApi.academicRecord(e.id,e.user_id,e.course_id);setRecord({enrollment:{...e,...fresh},...detail})}catch(x:any){setError(x.message||'Não foi possível abrir o histórico acadêmico.')}finally{setRecordBusy('')}}
 const issue=async(courseId:string)=>{try{setCertBusy(courseId);const cert=await academyApi.issueCertificate(courseId);if(cert?.id)await academyApi.certificatePdf(cert.id,'generate');setCertificates(await academyApi.myCertificates())}catch(e:any){setError(e.message||'Ainda não foi possível emitir o certificado.')}finally{setCertBusy('')}}
 const reissue=async(cert:any)=>{try{setCertBusy(cert.id);if(Number(cert.reissue_count||0)<3){const next=await academyApi.reissueCertificate(cert.id,'Nova via solicitada pelo aluno');if(next?.id)await academyApi.certificatePdf(next.id,'generate');setCertificates(await academyApi.myCertificates())}else{await academyApi.requestCertificateReissue(cert.id,'Nova via solicitada pelo aluno após o limite automático');setError('Solicitação enviada para análise. Você será notificado quando a nova via for liberada.')}}catch(e:any){setError(e.message||'Não foi possível solicitar a nova via.')}finally{setCertBusy('')}}
 const overall=rows.reduce((acc:any,row:any)=>{const s=stats[row.course_id]||{};acc.lessons+=s.total||0;acc.done+=s.done||0;return acc},{lessons:0,done:0});const overallPercent=overall.lessons?Math.round(overall.done/overall.lessons*100):0
 return <div className="max-w-6xl mx-auto">
  <CompactPageHeader eyebrow="Área do aluno" title="Minha Academia" description="Continue seus estudos e acompanhe o que precisa da sua atenção.">
    {rows.length>0&&<div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
      <div className="pm-compact-metric"><span className="text-[11px] text-gray-400">Cursos</span><b className="pm-compact-metric-value">{rows.length}</b></div>
      <div className="pm-compact-metric"><span className="text-[11px] text-gray-400">Aulas concluídas</span><b className="pm-compact-metric-value">{overall.done}<small className="ml-1 text-[11px] font-normal text-gray-500">/{overall.lessons}</small></b></div>
      <div className="pm-compact-metric"><span className="text-[11px] text-gray-400">Concluídos</span><b className="pm-compact-metric-value text-emerald-300">{completedCourses}</b></div>
      <div className="pm-compact-metric"><span className="text-[11px] text-gray-400">Termos pendentes</span><b className={'pm-compact-metric-value '+(pendingDocuments?'text-amber-300':'text-gray-200')}>{pendingDocuments}</b></div>
    </div>}
    {rows.length>0&&<p className="mt-1.5 text-[11px] text-gray-500">Progresso geral: {overallPercent}% · {rows.length-completedCourses} curso(s) em andamento</p>}
  </CompactPageHeader>
  {!loading&&academic?.student&&<section className="mb-3 pm-surface p-3 sm:p-4"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#ff5364]">Vida acadêmica</p><h2 className="text-lg font-bold mt-1">Registro acadêmico {academic.student.academic_record}</h2><p className="text-xs text-gray-500 mt-1">Acompanhe suas matrículas, matriz curricular, turma, nota final e conclusão.</p></div><div className="text-xs text-gray-500">{academic.enrollments.length} matrícula(s)</div></div><div className="grid md:grid-cols-2 gap-3 mt-4">{academic.enrollments.map((e:any)=><div key={e.id} className="rounded-xl border border-white/[.08] bg-black/20 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{e.course?.title||'Curso'}</p><p className="text-[10px] text-gray-500 mt-1">{e.enrollment_number||'Matrícula acadêmica'}</p></div><span className={"text-[10px] font-bold "+(e.status==='completed'?'text-emerald-300':'text-gray-400')}>{e.status==='completed'?'Concluída':'Em andamento'}</span></div><div className="grid grid-cols-2 gap-2 mt-3 text-[11px] text-gray-500"><span>Matriz: {e.curriculum?.name||'—'}</span><span>Oferta: {e.offering?.name||'—'}</span><span>Progresso: {Number(e.progress_percent||0)}%</span><span>Nota final: {e.final_grade??'—'}</span></div><button type="button" disabled={recordBusy===e.id} onClick={()=>void openRecord(e)} className="mt-3 text-[10px] font-bold text-[#ff6573] disabled:opacity-50">{recordBusy===e.id?'Atualizando…':'Boletim e histórico →'}</button></div>)}</div></section>}
  {!loading&&documents.filter((d:any)=>['contract','term'].includes(d.document_type)).length>0&&<section className="mb-3 pm-surface p-3 sm:p-4"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#ff5364]">Documentos e termos</p><h2 className="text-lg font-bold mt-1">Aceites acadêmicos</h2><p className="text-xs text-gray-500 mt-1">Confira os documentos emitidos para sua matrícula e registre seu aceite.</p></div><div className="mt-4 space-y-2">{documents.filter((d:any)=>['contract','term'].includes(d.document_type)).map((d:any)=><div key={d.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-xl border border-white/[.08] bg-black/20 p-3"><div><p className="text-sm font-semibold">{d.title}</p><p className="text-[10px] text-gray-500">Versão {d.current_version} · {d.document_type==='contract'?'Contrato':'Termo'} · {d.status==='signed'?'Aceito':'Aguardando aceite'}</p></div>{d.status!=='signed'&&<button type="button" disabled={docBusy===d.id} onClick={()=>void acceptDocument(d)} className="rounded-lg bg-[#A65A2A] px-3 py-2 text-[10px] font-bold text-white disabled:opacity-50">{docBusy===d.id?'Registrando…':'Li e aceito'}</button>}</div>)}</div></section>}
  {!loading&&continueRow&&<section className="mb-3 rounded-xl border border-white/10 bg-white/[.025] p-3 sm:p-4 flex flex-col md:flex-row md:items-center gap-4"><div className="flex-1"><p className="text-[10px] uppercase tracking-[.16em] text-[#ff5364]">Continuar estudando</p><h2 className="text-lg font-bold mt-1">{continueRow.course.title}</h2><p className="text-xs text-gray-500 mt-1">{stats[continueRow.course_id]?.percent||0}% concluído · {stats[continueRow.course_id]?.done||0}/{stats[continueRow.course_id]?.total||0} aulas</p><div className="h-1.5 rounded-full bg-white/[.06] mt-3 overflow-hidden max-w-xl"><div className="h-full bg-[#A65A2A]" style={{width:(stats[continueRow.course_id]?.percent||0)+'%'}}/></div></div><Link to={'/app/academia/'+continueRow.course_id} className="min-h-11 px-5 rounded-xl bg-[#A65A2A] text-white text-xs font-bold flex items-center justify-center">Continuar curso →</Link></section>}
  {loading?<LoadingState label="Organizando sua vida acadêmica..." />:error?<ErrorState message={error} action={<button onClick={()=>void load()} className="min-h-11 px-4 rounded-xl bg-white/5 text-xs font-bold">Tentar novamente</button>}/>:rows.length===0&&free.length===0?<div className="pm-surface p-8 md:p-12 text-center"><div className="w-12 h-12 rounded-2xl bg-[#A65A2A]/10 text-[#ff5364] flex items-center justify-center mx-auto text-xl">▶</div><h2 className="font-semibold mt-4">Nenhum conteúdo liberado ainda</h2><p className="text-sm text-gray-600 mt-2">Quando um curso ou treinamento for liberado para sua conta, ele aparecerá aqui.</p></div>:<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{rows.map((row:any)=>{const s=stats[row.course_id]||{total:0,done:0,percent:0,modules:0};return <Link key={row.id} to={'/app/academia/'+row.course.id} className="pm-surface pm-surface-interactive overflow-hidden group"><div className="aspect-video bg-white/[.025] relative">{row.course.cover_url?<img src={row.course.cover_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-3xl text-gray-700">▶</div>}<div className="absolute inset-x-0 bottom-0 h-1 bg-black/50"><div className="h-full bg-[#A65A2A]" style={{width:s.percent+'%'}}/></div></div><div className="p-4"><div className="flex items-center justify-between gap-3"><p className="text-[9px] uppercase tracking-wider text-[#ff5364]">{row.course.category||({course:'Curso',video_class:'Videoaula',webinar:'Webinar',lecture:'Palestra',training:'Treinamento'} as Record<string,string>)[row.course.content_type]||'Conteúdo'}</p><span className="text-[10px] text-gray-500">{s.percent}%</span></div><h2 className="font-semibold mt-1 group-hover:text-white">{row.course.title}</h2><div className="grid grid-cols-2 gap-2 mt-4 text-[11px] text-gray-500"><span>{s.modulesDone||0}/{s.modules} módulos</span><span className="text-right">{s.done}/{s.total} aulas</span></div><div className="h-1.5 rounded-full bg-white/[.05] mt-3 overflow-hidden"><div className="h-full rounded-full bg-[#A65A2A]" style={{width:s.percent+'%'}}/></div><div className="flex items-center justify-between gap-2 mt-3"><p className="text-xs text-gray-600">{(s.status||row.status)==='completed'?'Concluído':'Continuar curso →'}</p>{row.course.certificate_enabled&&(s.status||row.status)==='completed'&&(certificateFor(row.course_id)?<Link to={'/certificados/'+certificateFor(row.course_id).verification_code} onClick={e=>e.stopPropagation()} className="pm-tag pm-tag-success hover:border-emerald-400/40">Certificado emitido →</Link>:<button type="button" disabled={certBusy===row.course_id} onClick={e=>{e.preventDefault();e.stopPropagation();void issue(row.course_id)}} className="text-[10px] font-bold text-[#ff6573] disabled:opacity-50">{certBusy===row.course_id?'Emitindo…':'Emitir certificado'}</button>)}</div></div></Link>})}</div>}
  {!loading&&certificates.length>0&&<section className="mt-4"><div className="mb-3"><p className="text-[10px] uppercase tracking-[.16em] text-gray-600">Conquistas</p><h2 className="text-lg font-bold mt-1">Meus certificados</h2></div><div className="grid sm:grid-cols-2 gap-3">{certificates.map((cert:any)=><div key={cert.id} className="pm-surface p-4 flex items-center gap-4"><div className="w-11 h-11 rounded-xl bg-emerald-500/10 text-emerald-300 flex items-center justify-center text-lg">✓</div><div className="min-w-0"><p className="text-sm font-semibold truncate">{cert.course?.title||'Curso concluído'}</p><p className="text-[10px] text-gray-500 mt-1">{cert.course?.certificate_hours?cert.course.certificate_hours+' h · ':''}Emitido em {new Date(cert.issued_at).toLocaleDateString('pt-BR')}</p><p className="text-[9px] text-gray-600 mt-1">Código {cert.verification_code}</p><div className="flex flex-wrap gap-3 mt-2"><Link to={'/certificados/'+cert.verification_code} className="text-[10px] font-bold text-[#ff6573]">Visualizar certificado</Link><button type="button" disabled={certBusy===cert.id} onClick={()=>void reissue(cert)} className="text-[10px] text-gray-500 disabled:opacity-50">{certBusy===cert.id?'Processando…':Number(cert.reissue_count||0)<3?'Emitir '+(Number(cert.reissue_count||0)+2)+'ª via':'Solicitar nova via'}</button>{Number(cert.reissue_count||0)>0&&<span className="text-[9px] text-emerald-500">{Number(cert.reissue_count)+1}ª via vigente</span>}</div></div></div>)}</div></section>}
  {!loading&&free.length>0&&<section className="mt-4"><div className="mb-3"><p className="text-[10px] uppercase tracking-[.16em] text-gray-600">Disponíveis</p><h2 className="text-lg font-bold mt-1">Conteúdos gratuitos</h2></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{free.map((course:any)=><div key={course.id} className="pm-surface p-4"><p className="text-[9px] uppercase tracking-wider text-[#ff5364]">Gratuito</p><h3 className="font-semibold mt-1">{course.title}</h3><p className="text-xs text-gray-600 mt-2 line-clamp-2">{course.description||'Conteúdo disponível para sua conta.'}</p><button onClick={async()=>{await academyApi.selfEnroll(course.id);await load()}} className="mt-4 min-h-9 px-3 rounded-lg bg-[#A65A2A] text-white text-xs font-bold">Começar agora</button></div>)}</div></section>}

  {record&&<div className="fixed inset-0 z-[80] bg-black/75 p-3 md:p-8 overflow-auto"><div role="dialog" aria-modal="true" aria-label="Boletim e histórico acadêmico" className="mx-auto max-w-4xl rounded-2xl border border-white/10 bg-[#111113] p-5"><div className="flex justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] font-bold text-[#A65A2A]">Meu registro acadêmico</p><h3 className="text-xl font-bold">{record.enrollment.course?.title}</h3><p className="text-xs text-gray-500">{record.enrollment.enrollment_number}</p></div><button aria-label="Fechar boletim e histórico" onClick={()=>setRecord(null)} className="h-11 w-11 rounded-lg border border-white/10">✕</button></div><div className="grid sm:grid-cols-3 gap-2 mt-5">{[['Progresso',Number(record.enrollment.progress_percent||0)+'%'],['Nota final',record.enrollment.final_grade??'—'],['Situação',record.enrollment.status==='completed'?'Concluída':'Em andamento']].map(([a,b])=><div key={String(a)} className="rounded-xl bg-white/[.04] p-3"><p className="text-xs text-gray-500">{a}</p><b className="text-sm">{b}</b></div>)}</div><div className="mt-5 space-y-4">{record.modules.map((m:any)=>{const progress=new Map(record.progress.map((p:any)=>[p.lesson_id,p]));return <div key={m.id}><h4 className="text-sm font-bold">{m.title}</h4><div className="mt-2 space-y-1">{(m.course_lessons||[]).filter((l:any)=>l.status==='published').map((l:any)=><div key={l.id} className="flex justify-between rounded-lg bg-black/20 px-3 py-2 text-xs"><span>{l.title}</span><span>{(progress.get(l.id) as any)?.completed?'Concluída':'Pendente'}</span></div>)}</div></div>})}</div>{record.certificate&&<Link to={'/certificados/'+record.certificate.verification_code} className="mt-5 inline-flex rounded-xl bg-[#A65A2A] px-4 py-2 text-xs font-bold text-white">Abrir certificado</Link>}</div></div>}
 </div>
}
