import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { portalApi } from '../../api/portal'
export function DashboardPage(){
 const {user}=useAuth(); const [data,setData]=useState({orders:0,projects:0,quotes:0,payments:0,messages:0,notifications:0})
 useEffect(()=>{if(!user)return;Promise.all([portalApi.orders(),portalApi.projects(),portalApi.quotes(),portalApi.payments(),portalApi.unreadCounts(user.id)]).then(([o,p,q,pay,c])=>setData({orders:o.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length,projects:p.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length,quotes:q.filter((x:any)=>['sent','viewed'].includes(x.status)).length,payments:pay.filter((x:any)=>x.status!=='paid').length,messages:c.messages,notifications:c.notifications})).catch(()=>undefined)},[user?.id])
 const cards=[['Projetos ativos',data.projects,'📈','/app/projetos'],['Pedidos ativos',data.orders,'📦','/app/pedidos'],['Pagamentos pendentes',data.payments,'💳','/app/pagamentos'],['Orçamentos',data.quotes,'📋','/app/orcamentos'],['Mensagens não lidas',data.messages,'💬','/app/conversas'],['Notificações',data.notifications,'🔔','/app/notificacoes']]
 return <div><h1 className="text-2xl font-bold text-white">Olá, {user?.name} 👋</h1><p className="text-sm text-gray-500 mt-1 mb-7">Acompanhe seus trabalhos com a Play Moments.</p><div className="grid grid-cols-2 lg:grid-cols-3 gap-4">{cards.map(([label,value,icon,href])=><Link key={String(label)} to={String(href)} className="p-5 rounded-2xl bg-[#141416] border border-white/10"><span className="text-2xl">{icon}</span><p className="text-2xl font-bold text-[#E30613] mt-3">{value}</p><p className="text-xs text-gray-500">{label}</p></Link>)}</div><h2 className="font-bold mt-8 mb-3">Ações rápidas</h2><div className="flex flex-wrap gap-3"><Link className="px-4 py-3 rounded-xl bg-[#E30613]" to="/app/conversas">Falar com a Play Moments</Link><Link className="px-4 py-3 rounded-xl bg-white/5" to="/app/projetos">Meus projetos</Link><Link className="px-4 py-3 rounded-xl bg-white/5" to="/app/arquivos">Arquivos</Link></div></div>
}