import { supabase } from '../lib/supabase'

export type Course={id:string;title:string;slug:string;description:string|null;content_type:'course'|'video_class'|'webinar'|'lecture'|'training';status:'draft'|'published'|'archived';access_type:'free'|'manual'|'product';cover_url:string|null;cover_drive_file_id:string|null;instructor_name:string|null;estimated_minutes:number|null;created_at:string}
export const academyApi={
  async adminCourses(){const {data,error}=await supabase.from('courses').select('*').order('created_at',{ascending:false});if(error)throw error;return (data||[]) as Course[]},
  async freeCourses(){const {data,error}=await supabase.from('courses').select('*').eq('status','published').eq('access_type','free').order('published_at',{ascending:false});if(error)throw error;return data||[]},
  async selfEnroll(courseId:string){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão inválida.');const {data,error}=await supabase.from('course_enrollments').upsert({course_id:courseId,user_id:user.id,status:'active',source:'free'},{onConflict:'course_id,user_id'}).select().single();if(error)throw error;return data},
  async myCourses(){const {data,error}=await supabase.from('course_enrollments').select('*,course:courses(*)').in('status',['active','completed']).order('enrolled_at',{ascending:false});if(error)throw error;return data||[]},
  async saveCourse(course:Partial<Course>){const payload={...course,updated_at:new Date().toISOString()};if(course.id){const {id,...changes}=payload;const {data,error}=await supabase.from('courses').update(changes).eq('id',id).select().single();if(error)throw error;return data as Course}const {id,...insert}=payload;const {data,error}=await supabase.from('courses').insert(insert).select().single();if(error)throw error;return data as Course},
  async modules(courseId:string){const {data,error}=await supabase.from('course_modules').select('*,lessons:course_lessons(*)').eq('course_id',courseId).order('display_order').order('display_order',{referencedTable:'course_lessons'});if(error)throw error;return data||[]},
  async addModule(courseId:string,title:string){const {data,error}=await supabase.from('course_modules').insert({course_id:courseId,title}).select().single();if(error)throw error;return data},
  async addLesson(moduleId:string,title:string){const {data,error}=await supabase.from('course_lessons').insert({module_id:moduleId,title}).select().single();if(error)throw error;return data},
  async saveModule(module:any){const {id,...changes}=module;const {data,error}=await supabase.from('course_modules').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data},
  async saveLesson(lesson:any){const {id,...changes}=lesson;const {data,error}=await supabase.from('course_lessons').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data},
  async lessonMaterials(lessonId:string){const {data,error}=await supabase.from('lesson_materials').select('*').eq('lesson_id',lessonId).order('display_order');if(error)throw error;return data||[]},
  async addMaterial(material:any){const {data,error}=await supabase.from('lesson_materials').insert(material).select().single();if(error)throw error;return data},
  async courseForStudent(courseId:string){const {data:course,error}=await supabase.from('courses').select('*').eq('id',courseId).single();if(error)throw error;const modules=await this.modules(courseId);const {data:enrollment,error:enrollmentError}=await supabase.from('course_enrollments').select('*').eq('course_id',courseId).in('status',['active','completed']).maybeSingle();if(enrollmentError)throw enrollmentError;let progress:any[]=[];if(enrollment){const {data,error:progressError}=await supabase.from('lesson_progress').select('*').eq('enrollment_id',enrollment.id);if(progressError)throw progressError;progress=data||[]}return {course,modules,enrollment,progress}},
  async customers(){const {data,error}=await supabase.from('profiles').select('id,first_name,last_name,email').eq('role','customer').eq('status','active').order('first_name');if(error)throw error;return data||[]},
  async enrollments(courseId:string){const {data,error}=await supabase.from('course_enrollments').select('*,user:profiles(id,first_name,last_name,email)').eq('course_id',courseId).order('enrolled_at',{ascending:false});if(error)throw error;return data||[]},
  async enroll(courseId:string,userId:string){const {data,error}=await supabase.from('course_enrollments').upsert({course_id:courseId,user_id:userId,status:'active',source:'manual'},{onConflict:'course_id,user_id'}).select().single();if(error)throw error;return data},
  async setEnrollment(id:string,status:'active'|'completed'|'cancelled'){const {data,error}=await supabase.from('course_enrollments').update({status,completed_at:status==='completed'?new Date().toISOString():null}).eq('id',id).select().single();if(error)throw error;return data},
  async mediaTicket(kind:'lesson'|'material',id:string){const {data,error}=await supabase.functions.invoke('academy-drive-media',{body:{kind,id}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Não foi possível liberar a mídia.');return data},
  async uploadDrive(file:File,courseId:string,moduleId?:string,onProgress?:(value:number)=>void){const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:{course_id:courseId,module_id:moduleId||null,file_name:file.name,mime_type:file.type||'application/octet-stream',file_size:file.size}});if(error)throw error;if(!data?.upload_url)throw new Error(data?.error||'Não foi possível iniciar o upload.');return await new Promise<any>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',data.upload_url);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(Math.round(e.loaded/e.total*100))};xhr.onerror=()=>reject(new Error('Falha de conexão durante o upload.'));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){try{resolve(JSON.parse(xhr.responseText))}catch{reject(new Error('Resposta inválida do Google Drive.'))}}else reject(new Error('Google Drive recusou o upload ('+xhr.status+').'))};xhr.send(file)})},
  async setLessonComplete(enrollmentId:string,lessonId:string,completed:boolean){const payload={enrollment_id:enrollmentId,lesson_id:lessonId,completed,completed_at:completed?new Date().toISOString():null,last_watched_at:new Date().toISOString()};const {data,error}=await supabase.from('lesson_progress').upsert(payload,{onConflict:'enrollment_id,lesson_id'}).select().single();if(error)throw error;return data},

}
