import { supabase } from '../lib/supabase'

export type Course={id:string;title:string;slug:string;description:string|null;display_order?:number;content_type:'course'|'video_class'|'webinar'|'lecture'|'training';status:'draft'|'published'|'archived';access_type:'free'|'manual'|'product';cover_url:string|null;cover_drive_file_id:string|null;category:string|null;instructor_name:string|null;estimated_minutes:number|null;created_at:string}
async function functionError(error:any,fallback:string){
  try{const response=error?.context;if(response instanceof Response){const payload=await response.clone().json();return payload?.error||payload?.message||fallback}}catch{}
  return error?.message&&error.message!=='Edge Function returned a non-2xx status code'?error.message:fallback
}
export const academyApi={
  async adminCourses(){const {data,error}=await supabase.from('courses').select('*').order('display_order').order('created_at',{ascending:false});if(error)throw error;return (data||[]) as Course[]},
  async freeCourses(){const {data,error}=await supabase.from('courses').select('*').eq('status','published').eq('access_type','free').order('published_at',{ascending:false});if(error)throw error;return data||[]},
  async selfEnroll(courseId:string){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão inválida.');const {data,error}=await supabase.from('course_enrollments').upsert({course_id:courseId,user_id:user.id,status:'active',source:'free'},{onConflict:'course_id,user_id'}).select().single();if(error)throw error;return data},
  async myCourses(){const {data,error}=await supabase.from('course_enrollments').select('*,course:courses(*)').in('status',['active','completed']).order('enrolled_at',{ascending:false});if(error)throw error;return data||[]},
  async saveCourse(course:Partial<Course>){const payload={...course,updated_at:new Date().toISOString()};if(course.id){const {id,...changes}=payload;const {data,error}=await supabase.from('courses').update(changes).eq('id',id).select().single();if(error)throw error;return data as Course}const {id,...insert}=payload;const {data,error}=await supabase.from('courses').insert(insert).select().single();if(error)throw error;return data as Course},
  async modules(courseId:string){const {data,error}=await supabase.from('course_modules').select('*,lessons:course_lessons(*)').eq('course_id',courseId).order('display_order').order('display_order',{referencedTable:'course_lessons'});if(error)throw error;return data||[]},
  async deleteCourse(id:string){const {error}=await supabase.from('courses').delete().eq('id',id);if(error)throw error},
  async duplicateCourse(id:string){const source=await this.adminCourses().then(rows=>rows.find(c=>c.id===id));if(!source)throw new Error('Conteúdo não encontrado.');const {id:_id,created_at:_created,...copy}=source as any;return await this.saveCourse({...copy,title:source.title+' — Cópia',slug:source.slug+'-copia-'+Date.now(),status:'draft'})},
  async addModule(courseId:string,title:string){const {data,error}=await supabase.from('course_modules').insert({course_id:courseId,title}).select().single();if(error)throw error;return data},
  async deleteModule(id:string){const {error}=await supabase.from('course_modules').delete().eq('id',id);if(error)throw error},
  async duplicateModule(module:any){const {id:_id,lessons:_lessons,created_at:_created,updated_at:_updated,...copy}=module;const {data,error}=await supabase.from('course_modules').insert({...copy,title:module.title+' — Cópia'}).select().single();if(error)throw error;for(const lesson of module.lessons||[]){const {id:_lid,module_id:_mid,created_at:_lc,updated_at:_lu,...lessonCopy}=lesson;const {error:lessonError}=await supabase.from('course_lessons').insert({...lessonCopy,module_id:data.id,title:lesson.title+' — Cópia'});if(lessonError)throw lessonError}return data},
  async addLesson(moduleId:string,title:string){const {data,error}=await supabase.from('course_lessons').insert({module_id:moduleId,title}).select().single();if(error)throw error;return data},
  async deleteLesson(id:string){const {error}=await supabase.from('course_lessons').delete().eq('id',id);if(error)throw error},
  async duplicateLesson(lesson:any){const {id:_id,created_at:_created,updated_at:_updated,...copy}=lesson;const {data,error}=await supabase.from('course_lessons').insert({...copy,title:lesson.title+' — Cópia'}).select().single();if(error)throw error;return data},
  async reorderCourses(ids:string[]){const results=await Promise.all(ids.map((id,i)=>supabase.from('courses').update({display_order:i,updated_at:new Date().toISOString()}).eq('id',id)));const failed=results.find(r=>r.error);if(failed?.error)throw failed.error},
  async reorderModules(ids:string[]){const results=await Promise.all(ids.map((id,i)=>supabase.from('course_modules').update({display_order:i,updated_at:new Date().toISOString()}).eq('id',id)));const failed=results.find(r=>r.error);if(failed?.error)throw failed.error},
  async reorderLessons(ids:string[]){const results=await Promise.all(ids.map((id,i)=>supabase.from('course_lessons').update({display_order:i,updated_at:new Date().toISOString()}).eq('id',id)));const failed=results.find(r=>r.error);if(failed?.error)throw failed.error},
  async saveModule(module:any){const {id,...changes}=module;const {data,error}=await supabase.from('course_modules').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data},
  async saveLesson(lesson:any){const {id,...changes}=lesson;const {data,error}=await supabase.from('course_lessons').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data},
  async lessonMaterials(lessonId:string){const {data,error}=await supabase.from('lesson_materials').select('*').eq('lesson_id',lessonId).order('display_order');if(error)throw error;return data||[]},
  async addMaterial(material:any){const {data,error}=await supabase.from('lesson_materials').insert(material).select().single();if(error)throw error;return data},
  async updateMaterial(id:string,changes:any){const {data,error}=await supabase.from('lesson_materials').update(changes).eq('id',id).select().single();if(error)throw error;return data},
  async deleteMaterial(id:string,driveFileId?:string){if(driveFileId){const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:{action:'delete',drive_file_id:driveFileId}});if(error)throw new Error(await functionError(error,'Não foi possível excluir o arquivo do Drive.'));if(!data?.ok)throw new Error(data?.error||'Não foi possível excluir o arquivo do Drive.')}const {error}=await supabase.from('lesson_materials').delete().eq('id',id);if(error)throw error},
  async deleteDriveFile(driveFileId:string){const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:{action:'delete',drive_file_id:driveFileId}});if(error)throw new Error(await functionError(error,'Não foi possível excluir o arquivo do Drive.'));if(!data?.ok)throw new Error(data?.error||'Não foi possível excluir o arquivo do Drive.')},
  async courseForStudent(courseId:string){const {data:course,error}=await supabase.from('courses').select('*').eq('id',courseId).single();if(error)throw error;const modules=await this.modules(courseId);const {data:enrollment,error:enrollmentError}=await supabase.from('course_enrollments').select('*').eq('course_id',courseId).in('status',['active','completed']).maybeSingle();if(enrollmentError)throw enrollmentError;let progress:any[]=[];if(enrollment){const {data,error:progressError}=await supabase.from('lesson_progress').select('*').eq('enrollment_id',enrollment.id);if(progressError)throw progressError;progress=data||[]}return {course,modules,enrollment,progress}},
  async customers(){const {data,error}=await supabase.from('profiles').select('id,first_name,last_name,email').eq('role','customer').eq('status','active').order('first_name');if(error)throw error;return data||[]},
  async enrollments(courseId:string){const {data,error}=await supabase.from('course_enrollments').select('*,user:profiles(id,first_name,last_name,email)').eq('course_id',courseId).order('enrolled_at',{ascending:false});if(error)throw error;return data||[]},
  async enroll(courseId:string,userId:string){const {data,error}=await supabase.from('course_enrollments').upsert({course_id:courseId,user_id:userId,status:'active',source:'manual'},{onConflict:'course_id,user_id'}).select().single();if(error)throw error;return data},
  async setEnrollment(id:string,status:'active'|'completed'|'cancelled'){const {data,error}=await supabase.from('course_enrollments').update({status,completed_at:status==='completed'?new Date().toISOString():null}).eq('id',id).select().single();if(error)throw error;return data},
  async mediaTicket(kind:'lesson'|'material',id:string){const {data,error}=await supabase.functions.invoke('academy-drive-media',{body:{kind,id}});if(error)throw new Error(await functionError(error,'Não foi possível liberar a mídia.'));if(!data?.ok)throw new Error(data?.error||'Não foi possível liberar a mídia.');return data},
  async uploadDrive(file:File,courseId:string,moduleId?:string,onProgress?:(value:number)=>void,materialFolder?:string){const meta={course_id:courseId,module_id:moduleId||null,file_name:file.name,mime_type:file.type||'application/octet-stream',file_size:file.size,material_folder:materialFolder||null};const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:meta});if(error)throw new Error(await functionError(error,'Não foi possível iniciar o upload no Google Drive.'));if(!data?.upload_url)throw new Error(data?.error||'Não foi possível iniciar o upload.');return await new Promise<any>((resolve,reject)=>{let settled=false;const finish=(fn:()=>void)=>{if(settled)return;settled=true;fn()};const recover=async()=>{try{const {data:confirmed,error:confirmError}=await supabase.functions.invoke('academy-drive-upload-session',{body:{...meta,action:'confirm'}});if(confirmError)throw new Error(await functionError(confirmError,'Não foi possível confirmar o upload.'));if(!confirmed?.file?.id)throw new Error(confirmed?.error||'Arquivo enviado, mas não localizado no Drive.');onProgress?.(100);finish(()=>resolve(confirmed.file))}catch(e:any){finish(()=>reject(e))}};const xhr=new XMLHttpRequest();xhr.open('PUT',data.upload_url);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.setRequestHeader('Content-Range','bytes 0-'+(file.size-1)+'/'+file.size);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(Math.min(99,Math.round(e.loaded/e.total*99)))};xhr.onerror=()=>void recover();xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){try{finish(()=>resolve(JSON.parse(xhr.responseText)))}catch{void recover()}}else if(xhr.status===0||xhr.status===308)void recover();else finish(()=>reject(new Error('Google Drive recusou o upload ('+xhr.status+').')))};xhr.send(file)})},
  async setLessonComplete(enrollmentId:string,lessonId:string,completed:boolean){const payload={enrollment_id:enrollmentId,lesson_id:lessonId,completed,completed_at:completed?new Date().toISOString():null,last_watched_at:new Date().toISOString()};const {data,error}=await supabase.from('lesson_progress').upsert(payload,{onConflict:'enrollment_id,lesson_id'}).select().single();if(error)throw error;return data},

}
