import { supabase } from '../lib/supabase'

export type Course={id:string;title:string;slug:string;description:string|null;display_order?:number;content_type:'course'|'video_class'|'webinar'|'lecture'|'training';status:'draft'|'published'|'archived';access_type:'free'|'manual'|'product';cover_url:string|null;cover_drive_file_id:string|null;category:string|null;instructor_name:string|null;estimated_minutes:number|null;certificate_enabled?:boolean;certificate_hours?:number|null;require_assessments?:boolean;certificate_template_id?:string|null;created_at:string}
async function functionError(error:any,fallback:string){
  try{const response=error?.context;if(response instanceof Response){const payload=await response.clone().json();return payload?.error||payload?.message||fallback}}catch{}
  return error?.message&&error.message!=='Edge Function returned a non-2xx status code'?error.message:fallback
}
export const academyApi={
  async adminCourses(){const {data,error}=await supabase.from('courses').select('*').order('display_order').order('created_at',{ascending:false});if(error)throw error;return (data||[]) as Course[]},
  async freeCourses(){const {data,error}=await supabase.from('courses').select('*').eq('status','published').eq('access_type','free').order('published_at',{ascending:false});if(error)throw error;return data||[]},
  async selfEnroll(courseId:string){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão inválida.');const {data,error}=await supabase.from('course_enrollments').upsert({course_id:courseId,user_id:user.id,status:'active',source:'free'},{onConflict:'course_id,user_id'}).select().single();if(error)throw error;return data},
  async myCourses(){const {data,error}=await supabase.from('course_enrollments').select('*,course:courses(*)').in('status',['active','completed']).order('enrolled_at',{ascending:false});if(error)throw error;return data||[]},
  async saveCourse(course:Partial<Course>){const payload={...course,updated_at:new Date().toISOString()};if(course.id){const {id,...changes}=payload;const {data,error}=await supabase.from('courses').update(changes).eq('id',id).select().single();if(error)throw error;return data as Course}const {id,...insert}=payload;const {data,error}=await supabase.from('courses').insert(insert).select().single();if(error)throw error;return data as Course},
  async modules(courseId:string){const {data,error}=await supabase.from('course_modules').select('*,lessons:course_lessons(*)').eq('course_id',courseId).order('display_order').order('display_order',{referencedTable:'course_lessons'});if(error)throw error;return data||[]},
  async deleteCourse(id:string){const {error}=await supabase.from('courses').delete().eq('id',id);if(error)throw error},
  async duplicateCourse(id:string){const source=await this.adminCourses().then(rows=>rows.find(c=>c.id===id));if(!source)throw new Error('Conteúdo não encontrado.');const {id:_id,created_at:_created,...copy}=source as any;return await this.saveCourse({...copy,title:source.title+' — Cópia',slug:source.slug+'-copia-'+Date.now(),status:'draft'})},
  async addModule(courseId:string,title:string){const {data,error}=await supabase.from('course_modules').insert({course_id:courseId,title}).select().single();if(error)throw error;return data},
  async deleteModule(id:string){const {error}=await supabase.from('course_modules').delete().eq('id',id);if(error)throw error},
  async duplicateModule(module:any){const {id:_id,lessons:_lessons,created_at:_created,updated_at:_updated,...copy}=module;const {data,error}=await supabase.from('course_modules').insert({...copy,title:module.title+' — Cópia'}).select().single();if(error)throw error;for(const lesson of module.lessons||[]){const {id:_lid,module_id:_mid,created_at:_lc,updated_at:_lu,...lessonCopy}=lesson;const {error:lessonError}=await supabase.from('course_lessons').insert({...lessonCopy,module_id:data.id,title:lesson.title+' — Cópia'});if(lessonError)throw lessonError}return data},
  async addLesson(moduleId:string,title:string){const {data,error}=await supabase.from('course_lessons').insert({module_id:moduleId,title}).select().single();if(error)throw error;return data},
  async deleteLesson(id:string){const {error}=await supabase.from('course_lessons').delete().eq('id',id);if(error)throw error},
  async duplicateLesson(lesson:any){const {id:_id,created_at:_created,updated_at:_updated,...copy}=lesson;const {data,error}=await supabase.from('course_lessons').insert({...copy,title:lesson.title+' — Cópia'}).select().single();if(error)throw error;return data},
  async reorderCourses(ids:string[]){const results=await Promise.all(ids.map((id,i)=>supabase.from('courses').update({display_order:i,updated_at:new Date().toISOString()}).eq('id',id)));const failed=results.find(r=>r.error);if(failed?.error)throw failed.error},
  async reorderModules(ids:string[]){const results=await Promise.all(ids.map((id,i)=>supabase.from('course_modules').update({display_order:i,updated_at:new Date().toISOString()}).eq('id',id)));const failed=results.find(r=>r.error);if(failed?.error)throw failed.error},
  async reorderLessons(ids:string[]){const results=await Promise.all(ids.map((id,i)=>supabase.from('course_lessons').update({display_order:i,updated_at:new Date().toISOString()}).eq('id',id)));const failed=results.find(r=>r.error);if(failed?.error)throw failed.error},
  async saveModule(module:any){const {id,...changes}=module;const {data,error}=await supabase.from('course_modules').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data},
  async saveLesson(lesson:any){const {id,...changes}=lesson;const {data,error}=await supabase.from('course_lessons').update({...changes,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data},
  async lessonMaterials(lessonId:string){const {data,error}=await supabase.from('lesson_materials').select('*').eq('lesson_id',lessonId).order('display_order');if(error)throw error;return data||[]},
  async addMaterial(material:any){const {data,error}=await supabase.from('lesson_materials').insert(material).select().single();if(error)throw error;return data},
  async updateMaterial(id:string,changes:any){const {data,error}=await supabase.from('lesson_materials').update(changes).eq('id',id).select().single();if(error)throw error;return data},
  async deleteMaterial(id:string,driveFileId?:string){if(driveFileId){const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:{action:'delete',drive_file_id:driveFileId}});if(error)throw new Error(await functionError(error,'Não foi possível excluir o arquivo do Drive.'));if(!data?.ok)throw new Error(data?.error||'Não foi possível excluir o arquivo do Drive.')}const {error}=await supabase.from('lesson_materials').delete().eq('id',id);if(error)throw error},
  async deleteDriveFile(driveFileId:string){const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:{action:'delete',drive_file_id:driveFileId}});if(error)throw new Error(await functionError(error,'Não foi possível excluir o arquivo do Drive.'));if(!data?.ok)throw new Error(data?.error||'Não foi possível excluir o arquivo do Drive.')},
  async courseForStudent(courseId:string){const {data:course,error}=await supabase.from('courses').select('*').eq('id',courseId).single();if(error)throw error;const modules=await this.modules(courseId);const {data:enrollment,error:enrollmentError}=await supabase.from('course_enrollments').select('*').eq('course_id',courseId).in('status',['active','completed']).maybeSingle();if(enrollmentError)throw enrollmentError;let progress:any[]=[];if(enrollment){const {data,error:progressError}=await supabase.from('lesson_progress').select('*').eq('enrollment_id',enrollment.id);if(progressError)throw progressError;progress=data||[]}return {course,modules,enrollment,progress}},
  async customers(){const {data,error}=await supabase.from('profiles').select('id,first_name,last_name,email').eq('role','customer').eq('status','active').order('first_name');if(error)throw error;return data||[]},
  async enrollments(courseId:string){const {data,error}=await supabase.from('course_enrollments').select('*,user:profiles(id,first_name,last_name,email)').eq('course_id',courseId).order('enrolled_at',{ascending:false});if(error)throw error;return data||[]},
  async enroll(courseId:string,userId:string){const {data,error}=await supabase.from('course_enrollments').upsert({course_id:courseId,user_id:userId,status:'active',source:'manual'},{onConflict:'course_id,user_id'}).select().single();if(error)throw error;return data},
  async notifyCourseStudents(courseId:string,title:string,message:string,link?:string){const {data:rows,error}=await supabase.from('course_enrollments').select('user_id').eq('course_id',courseId).in('status',['active','completed']);if(error)throw error;const userIds=[...new Set((rows||[]).map((row:any)=>row.user_id).filter(Boolean))];if(!userIds.length)return 0;const {error:notifyError}=await supabase.from('notifications').insert(userIds.map(user_id=>({user_id,title,message,link:link||'/app/academia/'+courseId})));if(notifyError)throw notifyError;return userIds.length},
  async setEnrollment(id:string,status:'active'|'completed'|'cancelled'){const {data,error}=await supabase.from('course_enrollments').update({status,completed_at:status==='completed'?new Date().toISOString():null}).eq('id',id).select().single();if(error)throw error;return data},
  async mediaTicket(kind:'lesson'|'material',id:string){const {data,error}=await supabase.functions.invoke('academy-drive-media',{body:{kind,id}});if(error)throw new Error(await functionError(error,'Não foi possível liberar a mídia.'));if(!data?.ok)throw new Error(data?.error||'Não foi possível liberar a mídia.');return data},
  async uploadDrive(file:File,courseId:string,moduleId?:string,onProgress?:(value:number)=>void,materialFolder?:string){const meta={course_id:courseId,module_id:moduleId||null,file_name:file.name,mime_type:file.type||'application/octet-stream',file_size:file.size,material_folder:materialFolder||null};const {data,error}=await supabase.functions.invoke('academy-drive-upload-session',{body:meta});if(error)throw new Error(await functionError(error,'Não foi possível iniciar o upload no Google Drive.'));if(!data?.upload_url)throw new Error(data?.error||'Não foi possível iniciar o upload.');return await new Promise<any>((resolve,reject)=>{let settled=false;const finish=(fn:()=>void)=>{if(settled)return;settled=true;fn()};const recover=async()=>{try{const {data:confirmed,error:confirmError}=await supabase.functions.invoke('academy-drive-upload-session',{body:{...meta,action:'confirm'}});if(confirmError)throw new Error(await functionError(confirmError,'Não foi possível confirmar o upload.'));if(!confirmed?.file?.id)throw new Error(confirmed?.error||'Arquivo enviado, mas não localizado no Drive.');onProgress?.(100);finish(()=>resolve(confirmed.file))}catch(e:any){finish(()=>reject(e))}};const xhr=new XMLHttpRequest();xhr.open('PUT',data.upload_url);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.setRequestHeader('Content-Range','bytes 0-'+(file.size-1)+'/'+file.size);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(Math.min(99,Math.round(e.loaded/e.total*99)))};xhr.onerror=()=>void recover();xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){void recover()}else if(xhr.status===0||xhr.status===308)void recover();else finish(()=>reject(new Error('Google Drive recusou o upload ('+xhr.status+').')))};xhr.send(file)})},
  async certificateTemplates(){const {data,error}=await supabase.from('academy_certificate_templates').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]},
  async saveCertificateTemplate(template:any){const payload={...template,updated_at:new Date().toISOString()};if(template.id){const {id,...changes}=payload;const {data,error}=await supabase.from('academy_certificate_templates').update(changes).eq('id',id).select().single();if(error)throw error;return data}const {id,...insert}=payload;const {data,error}=await supabase.from('academy_certificate_templates').insert(insert).select().single();if(error)throw error;return data},
  async deleteCertificateTemplate(id:string){const {error}=await supabase.from('academy_certificate_templates').delete().eq('id',id);if(error)throw error;return true},
  async uploadCertificateAsset(file:File,kind:'background'|'signature',onProgress?:(value:number)=>void){onProgress?.(10);const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=kind+'/'+crypto.randomUUID()+'.'+ext;const {error}=await supabase.storage.from('academy-certificate-assets').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;onProgress?.(100);return {path}},
  async certificatePdf(certificateId:string,action:'generate'|'download'='download'){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sessão inválida.');const url=(import.meta.env.VITE_SUPABASE_URL||'')+'/functions/v1/academy-certificate-pdf';const response=await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({certificate_id:certificateId,action})});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||'Não foi possível gerar o certificado.')}if(action==='download'){const blob=await response.blob();const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='certificado.pdf';a.click();URL.revokeObjectURL(href);return true}return await response.json()},
  async myCertificates(){const {data,error}=await supabase.from('academy_certificates').select('*,course:courses(id,title,certificate_hours)').is('revoked_at',null).order('issued_at',{ascending:false});if(error)throw error;return data||[]},
  async issueCertificate(courseId:string){const {data,error}=await supabase.rpc('academy_issue_my_certificate',{p_course_id:courseId});if(error)throw error;return data},
  async cohorts(courseId:string){const {data,error}=await supabase.from('academy_cohorts').select('*,members:academy_cohort_members(user_id)').eq('course_id',courseId).order('created_at',{ascending:false});if(error)throw error;return data||[]},
  async createCohort(courseId:string,name:string,organization?:string){const {data,error}=await supabase.from('academy_cohorts').insert({course_id:courseId,name,organization:organization||null,status:'active'}).select().single();if(error)throw error;return data},
  async addCohortMember(cohortId:string,userId:string){const {error}=await supabase.from('academy_cohort_members').upsert({cohort_id:cohortId,user_id:userId});if(error)throw error},
  async setLessonComplete(enrollmentId:string,lessonId:string,completed:boolean){const payload={enrollment_id:enrollmentId,lesson_id:lessonId,completed,completed_at:completed?new Date().toISOString():null,last_watched_at:new Date().toISOString()};const {data,error}=await supabase.from('lesson_progress').upsert(payload,{onConflict:'enrollment_id,lesson_id'}).select().single();if(error)throw error;return data},

}
