import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { PublicLayout } from '../../layouts/PublicLayout'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'

function publicEmbed(source:string,url:string){
 if(source==='youtube'){const id=url.match(/(?:youtu\.be\/|v=|embed\/)([^?&/]+)/)?.[1];return id?`https://www.youtube.com/embed/${id}`:url}
 if(source==='vimeo'){const id=url.match(/vimeo\.com\/(?:video\/)?(\d+)/)?.[1];return id?`https://player.vimeo.com/video/${id}`:url}
 return url
}
export function PublicDigitalLiteracyPage(){
 const { isAuthenticated }=useAuth();const [data,setData]=useState<any>(null);const [active,setActive]=useState<any>(null);const [loading,setLoading]=useState(true)
 useEffect(()=>{supabase.rpc('academy_public_course',{course_slug:'letramento-digital'}).then(({data,error})=>{if(!error&&data){setData(data);setActive(data.modules?.[0]?.lessons?.[0]||null)}setLoading(false)})},[])
 const actionHref=isAuthenticated?'/app/academia':'/cadastro?next=%2Fapp%2Facademia'
 const lockedAction=(label:string)=><Link to={actionHref} className="w-full px-4 py-3 border-b border-white/[.04] text-left flex gap-3 items-center hover:bg-white/[.025]"><span className="w-6 h-6 rounded-full bg-white/[.05] text-gray-500 shrink-0 flex items-center justify-center text-[10px]">🔒</span><span className="min-w-0"><span className="block text-[10px] uppercase tracking-wider text-[#ff5364]">{label}</span><span className="block text-[10px] text-gray-500 mt-0.5">Entre ou crie sua conta gratuita para realizar</span></span></Link>
 return <PublicLayout><main className="px-5 py-10 max-w-7xl mx-auto">
  <div className="max-w-3xl mb-8"><span className="inline-flex px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-300 text-xs font-bold">Curso gratuito · acesso aberto</span><h1 className="text-3xl md:text-5xl font-extrabold mt-4 leading-tight">Letramento Digital <span className="text-[#E30613]">— tecnologia, autonomia e futuro</span></h1><p className="text-gray-400 mt-4 leading-relaxed">Entenda o mundo digital de forma prática e consciente. Assista sem cadastro. Para salvar seu progresso e participar das atividades, crie sua conta gratuita.</p></div>
  {loading?<p className="text-gray-500">Carregando curso...</p>:!data?<div className="pm-surface p-6">O curso está sendo preparado.</div>:<div className="grid xl:grid-cols-[1fr_360px] gap-5">
   <section><div className="aspect-video rounded-2xl bg-black border border-white/10 flex items-center justify-center overflow-hidden">{active?.video_url&&(active.video_source==='youtube'||active.video_source==='vimeo')?<iframe className="w-full h-full" src={publicEmbed(active.video_source,active.video_url)} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/>:<div className="text-center px-6"><div className="text-5xl text-[#E30613] mb-4">▶</div><p className="font-bold">{active?.title||'Aula'}</p><p className="text-sm text-gray-500 mt-2">O vídeo desta aula será publicado aqui.</p></div>}</div><div className="pm-surface p-5 mt-4"><p className="text-xs uppercase tracking-wider text-[#ff5364]">Aula aberta</p><h2 className="text-2xl font-bold mt-1">{active?.title}</h2><p className="text-sm text-gray-400 mt-3 leading-relaxed">{active?.description}</p><div className="mt-5 pt-4 border-t border-white/10 flex flex-wrap gap-3"><Link to={actionHref} className="px-5 min-h-11 inline-flex items-center rounded-xl bg-[#E30613] text-white text-sm font-bold">{isAuthenticated?'Ir para minha Academia':'Salvar progresso e fazer atividades'}</Link><span className="text-xs text-gray-500 self-center">Assistir é livre. Interações exigem conta.</span></div></div></section>
   <aside className="pm-surface overflow-hidden h-fit"><div className="p-4 border-b border-white/10"><p className="font-bold">Conteúdo do curso</p><p className="text-xs text-gray-500 mt-1">6 módulos · 12 aulas · gratuito</p></div>{data.modules?.map((m:any,i:number)=><div key={m.id}><div className="px-4 py-3 bg-white/[.025] border-b border-white/[.05]"><p className="text-[9px] uppercase text-gray-600">Módulo {i+1}</p><p className="text-xs font-semibold mt-1">{m.title}</p></div>{m.lessons?.map((l:any,j:number)=><button key={l.id} onClick={()=>setActive(l)} className={'w-full px-4 py-3 border-b border-white/[.04] text-left flex gap-3 hover:bg-white/[.03] '+(active?.id===l.id?'bg-red-500/[.06]':'')}><span className="w-6 h-6 rounded-full bg-white/[.05] text-gray-500 shrink-0 flex items-center justify-center text-[9px]">{j+1}</span><span className="text-xs text-gray-300 leading-5">{l.title}</span></button>)}{m.assessments?.map((a:any)=><div key={a.id}>{lockedAction((a.kind==='evaluation'?'Avaliação':'Atividade')+' · '+a.title)}</div>)}</div>)}<div>{lockedAction('Certificado · emitir após concluir o curso')}</div></aside>
  </div>}
 </main></PublicLayout>
}
