import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { PublicLayout } from '../../layouts/PublicLayout'
import { portalApi } from '../../api/portal'
import { useAuth } from '../../contexts/AuthContext'
import { useToast } from '../../contexts/ToastContext'
import { authLink } from '../../lib/navigation'
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100)
export function ServiceDetailPage(){const {slug}=useParams(),{user}=useAuth(),toast=useToast(),navigate=useNavigate();const [service,setService]=useState<any>(null),[loading,setLoading]=useState(true);useEffect(()=>{portalApi.services().then(rows=>setService(rows.find((x:any)=>x.slug===slug)||null)).finally(()=>setLoading(false))},[slug]);async function hire(){if(!service)return;if(!user){navigate(authLink('/cadastro','/servicos/'+service.slug));return}try{await portalApi.requestService(service.id);toast(service.price_type==='fixed'?'Pedido criado.':'Solicitação enviada.','success');navigate(service.price_type==='fixed'?'/app/pedidos':'/app/orcamentos')}catch(e:any){toast(e.message,'error')}}return <PublicLayout><div className="mx-auto px-4 py-12" style={{maxWidth:900}}>{loading?<p>Carregando...</p>:!service?<div><h1 className="text-2xl font-bold">Serviço não encontrado</h1><Link to="/servicos" className="text-[#E30613]">Voltar</Link></div>:<div><Link to="/servicos" className="text-sm text-gray-500">← Serviços</Link><h1 className="text-4xl font-bold mt-5">{service.name}</h1><p className="text-gray-400 mt-4 whitespace-pre-wrap">{service.description}</p><div className="mt-6 p-5 rounded-2xl bg-[#141416] border border-white/10"><p className="text-lg font-bold">{service.price_type==='quote'?'Preço sob consulta':(service.price_type==='starting_at'?'A partir de ':'')+money(service.price??service.starting_price??0)}</p><button onClick={hire} className="mt-4 px-5 py-3 rounded-xl bg-[#E30613] font-semibold">{service.price_type==='fixed'?'Contratar agora':'Solicitar orçamento'}</button></div></div>}</div></PublicLayout>}
