import { FormEvent,useEffect,useState } from 'react'
import { academyApi } from '../../api/academy'
const defaultLayout={student_name:{x:50,y:43,fontSize:30},body:{x:50,y:56,fontSize:14,width:72},signer:{x:72,y:79,fontSize:11},code:{x:50,y:92,fontSize:8},qr:{x:91,y:86,size:8}}
export function CertificateTemplateManager({onChanged}:{onChanged?:()=>void}){
 const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState<number|null>(null)
 const load=async()=>setRows(await academyApi.certificateTemplates());useEffect(()=>{void load().catch(e=>setError(e.message))},[])
 const fresh=()=>setForm({name:'Certificado padrão Play Moments',status:'draft',page_orientation:'landscape',body_template:'Certificamos que {{student_name}} concluiu o curso {{course_title}}, com carga horária de {{course_hours}} horas, em {{completion_date}}.',signer_name:'',signer_role:'',layout:defaultLayout})
 const save=async(e:FormEvent)=>{e.preventDefault();try{setBusy(true);await academyApi.saveCertificateTemplate(form);setForm(null);await load();onChanged?.()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const asset=async(file:File,kind:'background'|'signature')=>{try{setBusy(true);setProgress(0);const x=await academyApi.uploadCertificateAsset(file,kind,setProgress);setForm((v:any)=>({...v,[kind+'_drive_file_id']:x.id}))}catch(e:any){setError(e.message)}finally{setBusy(false);setProgress(null)}}
 const pos=(key:string,k:string,n:number)=>setForm((v:any)=>({...v,layout:{...v.layout,[key]:{...(v.layout?.[key]||{}),[k]:n}}}))
 return <section className="pm-surface p-5 mt-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-bold">Certificados</h2><p className="text-xs text-gray-500 mt-1">Modelos, timbrado, assinatura e posicionamento dos dados.</p></div><button onClick={fresh} className="min-h-10 px-4 rounded-xl bg-[#E30613] text-xs font-bold">+ Novo modelo</button></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{rows.map(t=><button key={t.id} onClick={()=>setForm({...t,layout:t.layout||defaultLayout})} className="text-left rounded-xl border border-white/10 p-3"><p className="text-sm font-semibold">{t.name}</p><p className="text-[10px] text-gray-500 mt-1">{t.status==='active'?'Ativo':t.status==='draft'?'Rascunho':'Arquivado'} · versão {t.version}</p></button>)}</div>
 {form&&<form onSubmit={save} className="mt-5 rounded-2xl border border-white/10 p-4"><div className="grid lg:grid-cols-2 gap-5"><div className="space-y-3"><label className="text-xs block">Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full min-h-10 rounded-lg bg-black/30 border border-white/10 px-3"/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full min-h-10 rounded-lg bg-[#171719] border border-white/10 px-3"><option value="draft">Rascunho</option><option value="active">Ativo</option><option value="archived">Arquivado</option></select></label><label className="text-xs">Página<select value={form.page_orientation} onChange={e=>setForm({...form,page_orientation:e.target.value})} className="mt-1 w-full min-h-10 rounded-lg bg-[#171719] border border-white/10 px-3"><option value="landscape">Paisagem</option><option value="portrait">Retrato</option></select></label></div><label className="text-xs block">Texto<textarea rows={4} value={form.body_template} onChange={e=>setForm({...form,body_template:e.target.value})} className="mt-1 w-full rounded-lg bg-black/30 border border-white/10 p-3"/></label><p className="text-[10px] text-gray-600">{'{{student_name}} · {{course_title}} · {{course_hours}} · {{completion_date}}'}</p><div className="grid grid-cols-2 gap-2"><label className="text-xs">Responsável<input value={form.signer_name||''} onChange={e=>setForm({...form,signer_name:e.target.value})} className="mt-1 w-full min-h-10 rounded-lg bg-black/30 border border-white/10 px-3"/></label><label className="text-xs">Cargo<input value={form.signer_role||''} onChange={e=>setForm({...form,signer_role:e.target.value})} className="mt-1 w-full min-h-10 rounded-lg bg-black/30 border border-white/10 px-3"/></label></div><div className="flex flex-wrap gap-2"><label className="px-3 min-h-10 rounded-lg bg-white/[.06] flex items-center text-xs cursor-pointer">Timbrado PDF/JPG/PNG<input hidden type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void asset(f,'background')}}/></label><label className="px-3 min-h-10 rounded-lg bg-white/[.06] flex items-center text-xs cursor-pointer">Assinatura PNG/JPG<input hidden type="file" accept="image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void asset(f,'signature')}}/></label></div>{progress!==null&&<p className="text-xs text-[#ff6573]">Upload {progress}%</p>}<div className="text-[10px] text-gray-500">Timbrado: {form.background_drive_file_id?'✓ configurado':'não enviado'} · Assinatura: {form.signature_drive_file_id?'✓ configurada':'não enviada'}</div></div>
 <div><p className="text-xs font-semibold mb-2">Posição no PDF (%)</p><div className="grid grid-cols-2 gap-2">{[['student_name','Nome'],['body','Texto'],['signer','Assinatura'],['code','Código'],['qr','QR']].map(([key,label])=><div key={key} className="rounded-lg border border-white/10 p-2"><p className="text-[10px] font-bold">{label}</p><div className="grid grid-cols-2 gap-1 mt-1"><label className="text-[9px]">X<input type="number" min="0" max="100" value={form.layout?.[key]?.x??50} onChange={e=>pos(key,'x',Number(e.target.value))} className="w-full bg-black/30 rounded px-2 py-1"/></label><label className="text-[9px]">Y<input type="number" min="0" max="100" value={form.layout?.[key]?.y??50} onChange={e=>pos(key,'y',Number(e.target.value))} className="w-full bg-black/30 rounded px-2 py-1"/></label></div></div>)}</div><div className={'mt-3 bg-white rounded-xl relative overflow-hidden '+(form.page_orientation==='portrait'?'aspect-[1/1.414] max-w-sm mx-auto':'aspect-[1.414/1]')}><p className="absolute text-black font-bold text-center w-full top-[40%]">NOME DO ALUNO</p><p className="absolute text-black/70 text-[10px] text-center inset-x-[12%] top-[54%]">Prévia de posicionamento. O timbrado original é preservado no PDF final.</p></div></div></div><div className="flex justify-end gap-2 mt-4"><button type="button" onClick={()=>setForm(null)} className="px-4 min-h-10">Cancelar</button><button disabled={busy} className="px-4 min-h-10 rounded-xl bg-[#E30613] text-xs font-bold">{busy?'Salvando…':'Salvar modelo'}</button></div></form>}
 {error&&<p className="text-xs text-red-300 mt-3">{error}</p>}</section>
}