import { useEffect,useState } from 'react'
import { portalApi } from '../../api/portal'
import { useToast } from '../../contexts/ToastContext'
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100)
export function AdminPayments(){
 const [rows,setRows]=useState<any[]>([]),[settings,setSettings]=useState<any>(null),[loading,setLoading]=useState(true); const toast=useToast()
 const load=async()=>{const [p,s]=await Promise.all([portalApi.payments(),portalApi.paymentSettings()]);setRows(p);setSettings(s);setLoading(false)}
 useEffect(()=>{void load()},[])
 async function review(id:string,status:'approved'|'rejected'){try{const note=status==='rejected'?window.prompt('Motivo da rejeição?')||'':'';await portalApi.reviewReceipt(id,status,note);toast('Comprovante atualizado.','success');await load()}catch(e:any){toast(e.message,'error')}}
 async function saveSettings(){if(!settings)return;try{await portalApi.savePaymentSettings({pix_key_type:settings.pix_key_type,pix_key:settings.pix_key,beneficiary_name:settings.beneficiary_name,bank_name:settings.bank_name,instructions:settings.instructions});toast('Dados PIX salvos.','success')}catch(e:any){toast(e.message,'error')}}
 return <div><h1 className="text-2xl font-bold text-white mb-2">Pagamentos</h1><p className="text-sm text-gray-500 mb-6">PIX manual, comprovantes e confirmações</p>
 {settings&&<div className="p-5 mb-6 rounded-2xl bg-[#141416] border border-white/10"><h2 className="font-bold mb-3">Configuração PIX</h2><div className="grid md:grid-cols-2 gap-3">{['pix_key_type','pix_key','beneficiary_name','bank_name'].map(k=><input key={k} value={settings[k]||''} onChange={e=>setSettings({...settings,[k]:e.target.value})} placeholder={k} className="px-3 py-2 rounded-lg bg-white/5 border border-white/10"/>)}</div><textarea value={settings.instructions||''} onChange={e=>setSettings({...settings,instructions:e.target.value})} placeholder="Instruções" className="mt-3 w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10"/><button onClick={saveSettings} className="mt-3 px-4 py-2 rounded-lg bg-[#E30613]">Salvar PIX</button></div>}
 {loading?<p>Carregando...</p>:<div className="space-y-3">{rows.map(p=><div key={p.id} className="p-4 rounded-2xl bg-[#141416] border border-white/10"><div className="flex flex-wrap justify-between gap-3"><div><b>{p.order?.order_number||'Pagamento'}</b><p className="text-sm text-gray-400">{money(p.amount)} · {p.method}</p></div><span>{p.status}</span></div>{p.receipt?.map((r:any)=><div key={r.id} className="mt-3 p-3 rounded-lg bg-white/5 flex justify-between items-center gap-3"><span className="text-sm">{r.file_name} · {r.status}</span>{r.status==='pending'&&<div className="flex gap-2"><button onClick={()=>review(r.id,'approved')} className="text-emerald-400">Confirmar</button><button onClick={()=>review(r.id,'rejected')} className="text-red-400">Rejeitar</button></div>}</div>)}</div>)}</div>}</div>
}