import { useEffect,useState } from 'react'
import { portalApi } from '../../api/portal'
import { useAuth } from '../../contexts/AuthContext'
import { useToast } from '../../contexts/ToastContext'
import { Button } from '../../components/ui/Button'
export function AdminFiles(){
 const {user}=useAuth(),toast=useToast();const [files,setFiles]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[loading,setLoading]=useState(true)
 const [customer,setCustomer]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false)
 const load=async()=>{const [f,c]=await Promise.all([portalApi.files(),portalApi.customers()]);setFiles(f);setCustomers(c);setLoading(false)};useEffect(()=>{void load()},[])
 async function save(e:React.FormEvent){e.preventDefault();if(!user||!customer||!name.trim()||(!url.trim()&&!file))return;try{setSaving(true);let storage_path:string|null=null;if(file)storage_path=await portalApi.uploadClientFile(customer,file);await portalApi.addClientFile({customer_id:customer,uploaded_by:user.id,name:name.trim(),external_url:url.trim()||null,storage_path,file_type:file?.type||null,client_visible:true});toast('Arquivo disponibilizado ao cliente.','success');setName('');setUrl('');setFile(null);await load()}catch(err:any){toast(err.message,'error')}finally{setSaving(false)}}
 return <div><h1 className="text-2xl font-bold">Arquivos</h1><p className="text-sm text-gray-500 mb-6">Disponibilize entregas e documentos aos clientes</p><form onSubmit={save} className="p-5 rounded-2xl bg-[#141416] border border-white/10 mb-6 grid md:grid-cols-2 gap-3"><select value={customer} onChange={e=>setCustomer(e.target.value)} className="px-3 py-2 rounded-xl bg-black border border-white/10"><option value="">Selecione o cliente</option>{customers.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name} — {c.email}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do arquivo" className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Link externo / Google Drive (opcional)" className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"/><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"/><div className="md:col-span-2"><Button type="submit" loading={saving}>Disponibilizar arquivo</Button></div></form>{loading?<p>Carregando...</p>:<div className="space-y-2">{files.map(f=><div key={f.id} className="p-4 rounded-2xl bg-[#141416] border border-white/10 flex justify-between gap-3"><div><b>{f.name}</b><p className="text-xs text-gray-500">{new Date(f.created_at).toLocaleString('pt-BR')}</p></div><span className="text-sm text-emerald-400">{f.client_visible?'Visível ao cliente':'Interno'}</span></div>)}</div>}</div>
}