import {useEffect,useState} from 'react'
import {portalApi} from '../../api/portal'
import {useToast} from '../../contexts/ToastContext'
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100)
export function AdminRentals(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);const toast=useToast()
 const load=()=>portalApi.rentals(true).then(setRows).finally(()=>setLoading(false));useEffect(()=>{void load()},[])
 async function change(id:string,status:'confirmed'|'checked_out'|'completed'|'cancelled'){try{await portalApi.updateRentalStatus(id,status);toast('Locação atualizada.','success');await load()}catch(e:any){toast(e.message||'Erro ao atualizar.','error')}}
 return <div><div className="mb-6"><p className="text-xs uppercase tracking-widest text-[#E30613]">Operação</p><h1 className="text-2xl font-bold">Locações</h1><p className="text-sm text-gray-500">Reservas, retiradas e devoluções.</p></div>{loading?<p>Carregando...</p>:<div className="space-y-2">{rows.map(r=><div key={r.id} className="p-4 rounded-2xl bg-[#141416] border border-white/10 flex flex-wrap justify-between gap-4"><div><b>{r.product?.name||'Produto'}</b><p className="text-xs text-gray-400">{r.customer?.first_name} {r.customer?.last_name} · {r.customer?.email}</p><p className="text-sm mt-1">{new Date(r.start_date+'T12:00:00').toLocaleDateString('pt-BR')} → {new Date(r.end_date+'T12:00:00').toLocaleDateString('pt-BR')} · {r.quantity} un.</p><p className="text-xs text-gray-500">{r.status} · {money(r.total_amount)}</p></div><div className="flex items-center gap-2">{r.status==='confirmed'&&<button onClick={()=>void change(r.id,'checked_out')} className="px-3 py-2 rounded-xl bg-blue-500/10 text-blue-300 text-xs">Registrar retirada</button>}{r.status==='checked_out'&&<button onClick={()=>void change(r.id,'completed')} className="px-3 py-2 rounded-xl bg-emerald-500/10 text-emerald-300 text-xs">Registrar devolução</button>}{!['completed','cancelled','checked_out'].includes(r.status)&&<button onClick={()=>void change(r.id,'cancelled')} className="px-3 py-2 rounded-xl border border-white/10 text-gray-500 text-xs">Cancelar</button>}</div></div>)}</div>}</div>
}