import {useEffect,useState} from 'react'
import {academyApi} from '../../api/academy'
import {useToast} from '../../contexts/ToastContext'

const field='w-full rounded-xl border border-white/10 bg-[#0d0d0f] px-3 py-2.5 text-sm text-gray-200'
const statusLabel:Record<string,string>={draft:'Rascunho',active:'Ativa',archived:'Arquivada'}

export function AdminAcademyPrograms(){
 const toast=useToast(),[rows,setRows]=useState<any[]>([]),[courses,setCourses]=useState<any[]>([]),[form,setForm]=useState({name:'',slug:'',program_type:'path',description:'',status:'draft'}),[selected,setSelected]=useState<any>(null),[courseId,setCourseId]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const [p,c]=await Promise.all([academyApi.programs(),academyApi.adminCourses()]);setRows(p);setCourses(c);setSelected((current:any)=>current?p.find((item:any)=>item.id===current.id)||null:current);return p}catch(e:any){toast(e.message,'error');return[]}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const create=async()=>{if(!form.name.trim()||!form.slug.trim())return toast('Informe nome e identificador da trilha.','error');try{await academyApi.createProgram({...form,name:form.name.trim(),slug:form.slug.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'')});setForm({name:'',slug:'',program_type:'path',description:'',status:'draft'});await load();toast('Trilha criada. Agora adicione os cursos que formam essa jornada.','success')}catch(e:any){toast(e.message,'error')}}
 const add=async()=>{if(!selected||!courseId)return;try{await academyApi.addProgramCourse({program_id:selected.id,course_id:courseId,position:(selected.courses?.length||0)+1,requirement_type:'required'});setCourseId('');await load();toast('Curso adicionado à trilha.','success')}catch(e:any){toast(e.message,'error')}}
 return <div className="space-y-5 text-gray-100">
  <div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#A65A2A]">Academia</p><h1 className="text-2xl font-bold">Trilhas de Formação</h1><p className="mt-1 max-w-3xl text-sm text-gray-400">Combine cursos existentes em uma jornada de aprendizagem. Cada curso mantém suas próprias aulas, atividades, avaliações e matrículas.</p></div>
  <div className="rounded-2xl border border-[#A65A2A]/20 bg-[#A65A2A]/[.04] p-4"><p className="text-sm font-semibold">Como funciona</p><p className="mt-1 text-xs leading-5 text-gray-400">Crie a trilha, abra a formação e escolha os cursos na ordem em que devem ser percorridos. A estrutura avançada de programas acadêmicos continua preparada no sistema, mas nesta V1 a operação foi simplificada para trilhas.</p></div>
  <div className="grid gap-4 xl:grid-cols-[380px_1fr]">
   <section className="space-y-3 rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><h2 className="font-semibold">Nova trilha</h2><input className={field} aria-label="Nome da trilha" placeholder="Nome da trilha" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={field} aria-label="Identificador da trilha" placeholder="Identificador (ex.: formacao-design-digital)" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><textarea className={field} aria-label="Descrição da trilha" placeholder="Descreva o objetivo desta jornada de aprendizagem" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button onClick={create} className="w-full rounded-xl bg-[#A65A2A] px-4 py-2.5 text-sm font-bold">Criar trilha</button><p className="text-[11px] leading-4 text-gray-500">Depois de criar, selecione a trilha ao lado para adicionar os cursos. Nenhuma aula será duplicada.</p></section>
   <section className="space-y-3 rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><div><h2 className="font-semibold">Trilhas existentes</h2><p className="text-xs text-gray-500">Clique em uma trilha para montar ou revisar sua jornada.</p></div>{loading?<p className="text-sm text-gray-500">Carregando trilhas...</p>:rows.length===0?<div className="rounded-xl border border-dashed border-white/10 p-6 text-center"><p className="text-sm font-medium">Nenhuma trilha criada</p><p className="mt-1 text-xs text-gray-500">Crie a primeira trilha somente quando quiser combinar dois ou mais cursos em uma formação.</p></div>:rows.map(p=><button key={p.id} onClick={()=>setSelected(p)} className="w-full rounded-xl border border-white/[.07] bg-black/20 p-3 text-left transition hover:border-[#A65A2A]/40"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold">{p.name}</div><div className="mt-1 text-xs text-gray-500">{p.courses?.length||0} curso(s) na jornada</div></div><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-gray-400">{statusLabel[p.status]||p.status}</span></div></button>)}</section>
  </div>
  {selected&&<div className="fixed inset-0 z-[80] overflow-auto bg-black/75 p-3 md:p-8" role="dialog" aria-modal="true" aria-label={'Montar trilha '+selected.name}><div className="mx-auto max-w-xl space-y-4 rounded-2xl border border-white/10 bg-[#111113] p-5"><div className="flex justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#A65A2A]">Montar jornada</p><h3 className="text-lg font-bold">{selected.name}</h3><p className="text-xs text-gray-500">Cursos que compõem esta trilha, na ordem de aprendizagem.</p></div><button onClick={()=>setSelected(null)} aria-label="Fechar" className="h-9 w-9 shrink-0 rounded-lg border border-white/10">✕</button></div>{(selected.courses||[]).length===0?<div className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-gray-500">Esta trilha ainda não possui cursos. Adicione o primeiro abaixo.</div>:[...(selected.courses||[])].sort((a:any,b:any)=>(a.position||0)-(b.position||0)).map((pc:any,index:number)=><div key={pc.id} className="flex items-center gap-3 rounded-xl bg-black/20 p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white/[.06] text-xs font-bold">{index+1}</span><div><p className="text-sm font-semibold">{pc.course?.title||'Curso'}</p><p className="text-[10px] text-gray-500">{pc.requirement_type==='required'?'Obrigatório':'Eletivo'}</p></div></div>)}<div className="flex flex-col gap-2 sm:flex-row"><select className={field} value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Selecione um curso para adicionar</option>{courses.filter(c=>!(selected.courses||[]).some((pc:any)=>pc.course_id===c.id)).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button disabled={!courseId} onClick={add} className="rounded-xl bg-[#A65A2A] px-4 py-2.5 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40">Adicionar</button></div></div></div>}
 </div>
}
