import { useEffect,useState } from 'react'
import { archiveCategory,createCategory,listCategories,updateCategory,type ProductCategoryRow } from '../../services/catalog'
import { useToast } from '../../contexts/ToastContext'
import { Button } from '../../components/ui/Button'
function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
export function AdminCategories(){
 const toast=useToast();const [rows,setRows]=useState<ProductCategoryRow[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<ProductCategoryRow|null>(null)
 const [form,setForm]=useState({name:'',description:'',active:true,display_order:0})
 const load=()=>listCategories().then(setRows).finally(()=>setLoading(false));useEffect(()=>{void load()},[])
 function start(row?:ProductCategoryRow){setEditing(row||null);setForm(row?{name:row.name,description:row.description||'',active:row.active,display_order:row.display_order}:{name:'',description:'',active:true,display_order:rows.length})}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.name.trim())return;try{const input={...form,name:form.name.trim(),slug:slugify(form.name),description:form.description.trim()||null};if(editing)await updateCategory(editing.id,input);else await createCategory(input);toast('Categoria salva.','success');setEditing(null);setForm({name:'',description:'',active:true,display_order:0});await load()}catch(err:any){toast(err.message,'error')}}
 async function disable(row:ProductCategoryRow){try{await archiveCategory(row.id);toast('Categoria desativada.','success');await load()}catch(err:any){toast(err.message,'error')}}
 return <div><div className="flex flex-wrap justify-between items-center gap-3 mb-6"><div><h1 className="text-2xl font-bold">Categorias</h1><p className="text-sm text-gray-500">Organize o catálogo de produtos</p></div><Button onClick={()=>start()}>Nova categoria</Button></div>
 {(editing||form.name||false)&&<form onSubmit={save} className="p-5 rounded-2xl bg-[#141416] border border-white/10 mb-5 grid md:grid-cols-2 gap-3"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome" className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"/><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descrição" className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"/><input type="number" value={form.display_order} onChange={e=>setForm({...form,display_order:Number(e.target.value)})} placeholder="Ordem" className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Ativa</label><div className="md:col-span-2 flex gap-2"><Button type="submit">Salvar</Button><Button type="button" variant="secondary" onClick={()=>{setEditing(null);setForm({name:'',description:'',active:true,display_order:0})}}>Cancelar</Button></div></form>}
 {loading?<p>Carregando...</p>:<div className="space-y-2">{rows.map(row=><div key={row.id} className="p-4 rounded-2xl bg-[#141416] border border-white/10 flex flex-wrap justify-between gap-3"><div><b>{row.name}</b><p className="text-xs text-gray-500">{row.slug} · ordem {row.display_order}</p><p className="text-sm text-gray-400 mt-1">{row.description}</p></div><div className="flex items-center gap-2"><span className={row.active?'text-emerald-400 text-sm':'text-gray-500 text-sm'}>{row.active?'Ativa':'Inativa'}</span><button onClick={()=>start(row)} className="px-3 py-2 rounded-lg bg-white/5">Editar</button>{row.active&&<button onClick={()=>disable(row)} className="px-3 py-2 rounded-lg text-red-400 bg-red-950/30">Desativar</button>}</div></div>)}</div>}</div>
}