import { useEffect,useState } from 'react'
import { portalApi } from '../../api/portal'
import { useAuth } from '../../contexts/AuthContext'
import { useToast } from '../../contexts/ToastContext'
import { prioridade,rotulo,statusProjeto,statusTarefa,tipoProjeto } from '../../lib/labels.ptBR'
function progress(p:any){const v=(p.tasks||[]).filter((t:any)=>t.status!=='cancelled');return v.length?Math.round(v.filter((t:any)=>t.status==='completed').length/v.length*100):0}
export function AdminProjects(){
 const {user}=useAuth(),toast=useToast(); const [rows,setRows]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[title,setTitle]=useState(''),[customer,setCustomer]=useState('')
 const load=async()=>{const [p,c]=await Promise.all([portalApi.projects(),portalApi.customers()]);setRows(p);setCustomers(c)}
 useEffect(()=>{void load()},[])
 async function create(){if(!user||!title.trim())return;try{await portalApi.saveProject({title:title.trim(),project_type:'other',customer_id:customer||null,status:'planning',priority:'medium',created_by:user.id});setTitle('');toast('Projeto criado.','success');await load()}catch(e:any){toast(e.message,'error')}}
 async function task(projectId:string){if(!user)return;const name=window.prompt('Nome da tarefa');if(!name)return;try{await portalApi.saveTask({project_id:projectId,title:name,status:'pending',priority:'medium',created_by:user.id,client_visible:true});await load()}catch(e:any){toast(e.message,'error')}}
 return <div><h1 className="text-2xl font-bold text-white mb-2">Projetos e Produtividade</h1><p className="text-sm text-gray-500 mb-6">Acompanhe trabalhos, progresso e tarefas</p>
 <div className="p-4 rounded-2xl bg-[#141416] border border-white/10 mb-5 flex flex-wrap gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Novo projeto" className="px-3 py-2 rounded-lg bg-white/5 border border-white/10"/><select value={customer} onChange={e=>setCustomer(e.target.value)} className="px-3 py-2 rounded-lg bg-black border border-white/10"><option value="">Projeto interno</option>{customers.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select><button onClick={create} className="px-4 py-2 rounded-lg bg-[#E30613]">Criar</button></div>
 <div className="grid lg:grid-cols-2 gap-4">{rows.map(p=><div key={p.id} className="p-5 rounded-2xl bg-[#141416] border border-white/10"><div className="flex justify-between gap-3"><div><b>{p.title}</b><p className="text-xs text-gray-500 mt-1">{rotulo(tipoProjeto,p.project_type)} · prioridade {rotulo(prioridade,p.priority)}</p></div><span className="text-sm">{rotulo(statusProjeto,p.status)}</span></div><p className="text-sm text-gray-500 mt-2">{progress(p)}% concluído</p><div className="h-2 bg-white/10 rounded mt-2"><div className="h-2 bg-[#E30613] rounded" style={{width:progress(p)+'%'}}/></div><div className="mt-4 space-y-2">{(p.tasks||[]).map((t:any)=><div key={t.id} className="flex justify-between gap-2 p-2 rounded bg-white/5 text-sm"><span>{t.title}</span><select value={t.status} onChange={async e=>{await portalApi.saveTask({status:e.target.value,completed_at:e.target.value==='completed'?new Date().toISOString():null},t.id);await load()}} className="bg-black"><option value="pending">{rotulo(statusTarefa,'pending')}</option><option value="in_progress">{rotulo(statusTarefa,'in_progress')}</option><option value="review">{rotulo(statusTarefa,'review')}</option><option value="completed">{rotulo(statusTarefa,'completed')}</option><option value="cancelled">{rotulo(statusTarefa,'cancelled')}</option></select></div>)}</div><button onClick={()=>task(p.id)} className="mt-3 text-sm text-[#E30613]">+ Nova tarefa</button></div>)}</div></div>
}