import { useEffect,useMemo,useState } from 'react'
import { academyApi } from '../../api/academy'
import { useToast } from '../../contexts/ToastContext'
type Tab='curricula'|'offerings'|'enroll'
const field='w-full rounded-xl border border-white/10 bg-[#0d0d0f] px-3 py-2.5 text-sm text-gray-200 outline-none focus:border-[#E30613]'
export function AdminAcademyManagement(){
 const toast=useToast(),[tab,setTab]=useState<Tab>('curricula'),[courses,setCourses]=useState<any[]>([]),[curricula,setCurricula]=useState<any[]>([]),[offerings,setOfferings]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[loading,setLoading]=useState(true)
 const [curr,setCurr]=useState<any>({course_id:'',name:'',effective_from:'',status:'draft'}),[offer,setOffer]=useState<any>({course_id:'',curriculum_id:'',name:'',offering_type:'open',status:'draft',starts_on:'',ends_on:'',seats:''}),[enroll,setEnroll]=useState({course_id:'',offering_id:'',user_id:''})
 const load=async()=>{setLoading(true);try{const [c,cu,o,u]=await Promise.all([academyApi.adminCourses(),academyApi.curricula(),academyApi.offerings(),academyApi.customers()]);setCourses(c);setCurricula(cu);setOfferings(o);setCustomers(u)}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const courseName=(id:string)=>courses.find(c=>c.id===id)?.title||'Curso'
 const saveCurr=async()=>{if(!curr.course_id)return toast('Selecione o curso.','error');try{await academyApi.createCurriculum(curr);toast('Nova versão de matriz criada.','success');setCurr({course_id:'',name:'',effective_from:'',status:'draft'});await load()}catch(e:any){toast(e.message,'error')}}
 const saveOffer=async()=>{if(!offer.course_id||!offer.curriculum_id)return toast('Selecione curso e matriz.','error');try{await academyApi.createOffering(offer);toast('Oferta/turma criada.','success');setOffer({course_id:'',curriculum_id:'',name:'',offering_type:'open',status:'draft',starts_on:'',ends_on:'',seats:''});await load()}catch(e:any){toast(e.message,'error')}}
 const doEnroll=async()=>{if(!enroll.user_id||!enroll.offering_id)return toast('Selecione aluno e oferta.','error');try{await academyApi.academicEnroll(enroll.user_id,enroll.offering_id);toast('Matrícula acadêmica criada.','success');setEnroll({course_id:'',offering_id:'',user_id:''});await load()}catch(e:any){toast(e.message,'error')}}
 const filteredCurr=useMemo(()=>curricula.filter(x=>!offer.course_id||x.course_id===offer.course_id),[curricula,offer.course_id]); const filteredOffers=offerings.filter(x=>!enroll.course_id||x.course_id===enroll.course_id)
 return <div className="space-y-5 text-gray-100"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#E30613]">Academia</p><h1 className="text-2xl font-bold">Gestão acadêmica</h1><p className="text-sm text-gray-500">Matrizes, ofertas/turmas e matrícula administrativa em um único fluxo.</p></div>
 <div className="flex flex-wrap gap-2">{([['curricula','Matrizes'],['offerings','Ofertas / Turmas'],['enroll','Nova matrícula']] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={'rounded-xl px-4 py-2 text-sm font-semibold '+(tab===k?'bg-[#E30613] text-white':'border border-white/10 bg-white/[.03] text-gray-400')}>{l}</button>)}</div>
 {loading?<div className="text-sm text-gray-500">Carregando...</div>:tab==='curricula'?<div className="grid xl:grid-cols-[380px_1fr] gap-4"><Panel title="Criar nova versão"><select className={field} value={curr.course_id} onChange={e=>setCurr({...curr,course_id:e.target.value})}><option value="">Curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><input className={field} placeholder="Nome da matriz (opcional)" value={curr.name} onChange={e=>setCurr({...curr,name:e.target.value})}/><input type="date" className={field} value={curr.effective_from} onChange={e=>setCurr({...curr,effective_from:e.target.value})}/><select className={field} value={curr.status} onChange={e=>setCurr({...curr,status:e.target.value})}><option value="draft">Rascunho</option><option value="active">Ativa</option></select><Action onClick={saveCurr}>Criar matriz</Action></Panel><Panel title="Matrizes existentes">{curricula.map(x=><Row key={x.id} title={x.name} meta={courseName(x.course_id)+' · Versão '+x.version+' · '+x.status}/>)}</Panel></div>
 :tab==='offerings'?<div className="grid xl:grid-cols-[380px_1fr] gap-4"><Panel title="Nova oferta / turma"><select className={field} value={offer.course_id} onChange={e=>setOffer({...offer,course_id:e.target.value,curriculum_id:''})}><option value="">Curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select className={field} value={offer.curriculum_id} onChange={e=>setOffer({...offer,curriculum_id:e.target.value})}><option value="">Matriz</option>{filteredCurr.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={field} placeholder="Nome da oferta/turma" value={offer.name} onChange={e=>setOffer({...offer,name:e.target.value})}/><div className="grid grid-cols-2 gap-2"><select className={field} value={offer.offering_type} onChange={e=>setOffer({...offer,offering_type:e.target.value})}><option value="open">Contínua</option><option value="cohort">Turma</option><option value="private">Privada</option></select><input type="number" min="1" className={field} placeholder="Vagas" value={offer.seats} onChange={e=>setOffer({...offer,seats:e.target.value})}/><input type="date" className={field} value={offer.starts_on} onChange={e=>setOffer({...offer,starts_on:e.target.value})}/><input type="date" className={field} value={offer.ends_on} onChange={e=>setOffer({...offer,ends_on:e.target.value})}/></div><Action onClick={saveOffer}>Criar oferta</Action></Panel><Panel title="Ofertas existentes">{offerings.map(x=><Row key={x.id} title={x.name} meta={courseName(x.course_id)+' · '+x.offering_type+' · '+x.status+' · '+(x.enrollments?.[0]?.count??0)+' matrícula(s)'}/>)}</Panel></div>
 :<div className="max-w-xl"><Panel title="Matrícula administrativa"><select className={field} value={enroll.user_id} onChange={e=>setEnroll({...enroll,user_id:e.target.value})}><option value="">Aluno / cliente</option>{customers.map(u=><option key={u.id} value={u.id}>{[u.first_name,u.last_name].filter(Boolean).join(' ')||u.email}</option>)}</select><select className={field} value={enroll.course_id} onChange={e=>setEnroll({...enroll,course_id:e.target.value,offering_id:''})}><option value="">Curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select className={field} value={enroll.offering_id} onChange={e=>setEnroll({...enroll,offering_id:e.target.value})}><option value="">Oferta / turma</option>{filteredOffers.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><p className="text-xs text-gray-500">O sistema gera RA quando necessário, número de matrícula, vínculo com matriz/oferta e evento acadêmico.</p><Action onClick={doEnroll}>Efetivar matrícula</Action></Panel></div>}</div>
}
function Panel({title,children}:{title:string;children:any}){return <section className="rounded-2xl border border-white/[.08] bg-white/[.025] p-4 space-y-3"><h2 className="font-semibold">{title}</h2>{children}</section>}
function Row({title,meta}:{title:string;meta:string}){return <div className="rounded-xl border border-white/[.07] bg-black/20 p-3"><div className="text-sm font-semibold">{title}</div><div className="text-xs text-gray-500 mt-1">{meta}</div></div>}
function Action({onClick,children}:{onClick:()=>void;children:any}){return <button onClick={onClick} className="w-full rounded-xl bg-[#E30613] px-4 py-2.5 text-sm font-bold text-white hover:brightness-110">{children}</button>}
