import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { portalApi } from '../../api/portal'
export function AdminDashboard(){
 const {user}=useAuth(); const [d,setD]=useState({customers:0,projects:0,orders:0,payments:0,quotes:0,messages:0})
 useEffect(()=>{if(!user)return;Promise.all([portalApi.customers(),portalApi.projects(),portalApi.orders(),portalApi.payments(),portalApi.quotes(),portalApi.unreadCounts(user.id)]).then(([c,p,o,pay,q,u])=>setD({customers:c.length,projects:p.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length,orders:o.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length,payments:pay.filter((x:any)=>x.status==='awaiting_confirmation').length,quotes:q.filter((x:any)=>['draft','sent','viewed'].includes(x.status)).length,messages:u.messages})).catch(()=>undefined)},[user?.id])
 const cards=[['Clientes',d.customers,'👥','/admin/clientes'],['Projetos ativos',d.projects,'📈','/admin/projetos'],['Pedidos ativos',d.orders,'🛒','/admin/pedidos'],['Comprovantes',d.payments,'💳','/admin/pagamentos'],['Orçamentos',d.quotes,'📋','/admin/orcamentos'],['Mensagens não lidas',d.messages,'💬','/admin/conversas']]
 return <div><h1 className="text-2xl font-bold text-white mb-2">Dashboard</h1><p className="text-sm text-gray-500 mb-6">Visão real da operação Play Moments</p><div className="grid grid-cols-2 lg:grid-cols-3 gap-4">{cards.map(([l,v,i,h])=><Link key={String(l)} to={String(h)} className="p-5 rounded-2xl bg-[#141416] border border-white/10"><span className="text-2xl">{i}</span><p className="text-2xl font-bold text-[#E30613] mt-3">{v}</p><p className="text-xs text-gray-500">{l}</p></Link>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/admin/produtividade" className="px-4 py-3 rounded-xl bg-[#E30613]">Produtividade</Link><Link to="/admin/conversas" className="px-4 py-3 rounded-xl bg-white/5">Central de chat</Link><Link to="/admin/pagamentos" className="px-4 py-3 rounded-xl bg-white/5">Pagamentos</Link></div></div>
