import { useEffect,useState } from 'react'
import { academyApi,Course } from '../../api/academy'
import { useToast } from '../../contexts/ToastContext'

const labels:Record<string,string>={course:'Curso',video_class:'Videoaula',webinar:'Webinar',lecture:'Palestra',training:'Treinamento',draft:'Rascunho',published:'Publicado',archived:'Arquivado'}
export function AdminAcademy(){
 const {toast}=useToast();const [courses,setCourses]=useState<Course[]>([]);const [selected,setSelected]=useState<Course|null>(null);const [modules,setModules]=useState<any[]>([]);const [loading,setLoading]=useState(true)
 const load=async()=>{try{setCourses(await academyApi.adminCourses())}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const open=async(course:Course)=>{setSelected(course);try{setModules(await academyApi.modules(course.id))}catch(e:any){toast(e.message,'error')}}
 const create=async()=>{const title=window.prompt('Nome do curso ou conteúdo');if(!title)return;try{const course=await academyApi.saveCourse({title,slug:title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),content_type:'course',status:'draft',access_type:'manual'});await load();await open(course)}catch(e:any){toast(e.message,'error')}}
 const addModule=async()=>{if(!selected)return;const title=window.prompt('Nome do módulo');if(!title)return;await academyApi.addModule(selected.id,title);setModules(await academyApi.modules(selected.id))}
 const addLesson=async(moduleId:string)=>{const title=window.prompt('Nome da aula');if(!title)return;await academyApi.addLesson(moduleId,title);if(selected)setModules(await academyApi.modules(selected.id))}
 return <div className="max-w-7xl mx-auto">
  <div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#E30613] font-bold">Conteúdo</p><h1 className="text-2xl md:text-3xl font-bold mt-1">Academia Play Moments</h1><p className="text-sm text-gray-500 mt-1">Cursos, videoaulas, webinars, palestras e treinamentos.</p></div><button onClick={create} className="min-h-11 px-4 rounded-xl bg-[#E30613] text-white text-sm font-bold">＋ Novo conteúdo</button></div>
  {loading?<p className="text-sm text-gray-500">Carregando...</p>:<div className="grid lg:grid-cols-[360px_1fr] gap-4">
   <section className="pm-surface overflow-hidden"><div className="p-4 border-b border-white/8"><p className="text-xs uppercase tracking-wider text-gray-500">{courses.length} conteúdo(s)</p></div>{courses.length===0?<div className="p-6 text-sm text-gray-500">Nenhum conteúdo cadastrado.</div>:courses.map(c=><button key={c.id} onClick={()=>void open(c)} className={'w-full text-left p-4 border-b border-white/[.05] hover:bg-white/[.025] '+(selected?.id===c.id?'bg-white/[.035]':'')}><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{c.title}</p><span className="text-[9px] text-gray-500">{labels[c.status]}</span></div><p className="text-[10px] text-gray-600 mt-1">{labels[c.content_type]} · {c.access_type==='free'?'Gratuito':c.access_type==='product'?'Produto':'Liberação manual'}</p></button>)}</section>
   <section className="pm-surface min-h-[420px]">{!selected?<div className="h-full min-h-[420px] flex items-center justify-center text-center p-8"><div><p className="text-lg font-semibold">Selecione um conteúdo</p><p className="text-sm text-gray-600 mt-2">Edite módulos e aulas sem sair desta tela.</p></div></div>:<div><div className="p-5 border-b border-white/8 flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-gray-600">{labels[selected.content_type]}</p><h2 className="text-xl font-bold mt-1">{selected.title}</h2></div><button onClick={addModule} className="px-3 min-h-9 rounded-lg border border-white/10 text-xs">＋ Módulo</button></div><div className="p-5 space-y-3">{modules.length===0?<div className="border border-dashed border-white/10 rounded-2xl p-8 text-center text-sm text-gray-600">Crie o primeiro módulo para começar a organizar as aulas.</div>:modules.map((m:any,i:number)=><div key={m.id} className="rounded-xl border border-white/8 bg-black/20"><div className="p-4 flex items-center justify-between"><div><p className="text-[9px] uppercase text-gray-600">Módulo {i+1}</p><p className="text-sm font-semibold mt-1">{m.title}</p></div><button onClick={()=>void addLesson(m.id)} className="text-xs text-[#ff5364]">＋ Aula</button></div>{(m.lessons||[]).map((l:any,j:number)=><div key={l.id} className="px-4 py-3 border-t border-white/[.05] flex items-center gap-3"><span className="w-6 h-6 rounded-full bg-white/[.04] text-[9px] flex items-center justify-center text-gray-500">{j+1}</span><span className="text-xs text-gray-300">{l.title}</span><span className="ml-auto text-[9px] text-gray-600">{labels[l.status]}</span></div>)}</div>)}</div></div>}</section>
  </div>}
 </div>
}
