import { useEffect,useState } from 'react'
import { Button } from '../../components/ui/Button'
import { Input } from '../../components/ui/Input'
import { useToast } from '../../contexts/ToastContext'
import { siteContentApi,type SiteCampaign,type SiteLandingPage,type LandingSection } from '../../services/siteContent'

const blank={title:'',slug:'',headline:'',subheadline:'',eyebrow:'',cta_label:'Quero esta solução',cta_href:'/contato',secondary_cta_label:'',secondary_cta_href:'',status:'draft' as SiteLandingPage['status'],campaign_id:'',seo_title:'',seo_description:'',noindex:false,hero_image_url:'',hero_image_drive_file_id:'',hero_image_mime_type:'',hero_image_file_size:null as number|null}
const parse=(text:string)=>text.split('\n').map(v=>v.trim()).filter(Boolean).map(v=>{const [title,...rest]=v.split('|');return {title:title.trim(),description:rest.join('|').trim()||undefined}})

export function AdminLandingPages(){
 const toast=useToast(),[pages,setPages]=useState<SiteLandingPage[]>([]),[campaigns,setCampaigns]=useState<SiteCampaign[]>([]),[form,setForm]=useState({...blank}),[editing,setEditing]=useState<string|null>(null),[benefits,setBenefits]=useState(''),[proof,setProof]=useState(''),[objections,setObjections]=useState(''),[faq,setFaq]=useState(''),[finalCta,setFinalCta]=useState(''),[saving,setSaving]=useState(false)
 const load=()=>Promise.all([siteContentApi.landingPages(true),siteContentApi.campaigns()]).then(([p,c])=>{setPages(p);setCampaigns(c)})
 useEffect(()=>{load().catch((e:any)=>toast(e.message,'error'))},[])
 const set=(k:keyof typeof form)=>(e:any)=>setForm(v=>({...v,[k]:e.target.value}))
 function reset(){setForm({...blank});setEditing(null);setBenefits('');setProof('');setObjections('');setFaq('');setFinalCta('')}
 function edit(p:SiteLandingPage){setEditing(p.id);setForm({...blank,...p,campaign_id:p.campaign_id||'',subheadline:p.subheadline||'',eyebrow:p.eyebrow||'',secondary_cta_label:p.secondary_cta_label||'',secondary_cta_href:p.secondary_cta_href||'',seo_title:p.seo_title||'',seo_description:p.seo_description||'',hero_image_url:p.hero_image_url||'',hero_image_drive_file_id:p.hero_image_drive_file_id||'',hero_image_mime_type:p.hero_image_mime_type||'',hero_image_file_size:p.hero_image_file_size});const get=(type:LandingSection['type'])=>p.sections.find(s=>s.type===type);setBenefits((get('benefits')?.items||[]).map(i=>i.title+(i.description?' | '+i.description:'')).join('\n'));setProof((get('proof')?.items||[]).map(i=>i.title+(i.description?' | '+i.description:'')).join('\n'));const content=p.sections.filter(s=>s.type==='content');setObjections((content[0]?.items||[]).map(i=>i.title+(i.description?' | '+i.description:'')).join('\n'));setFaq((get('faq')?.items||[]).map(i=>i.title+(i.description?' | '+i.description:'')).join('\n'));setFinalCta(get('cta')?.text||'');window.scrollTo({top:0,behavior:'smooth'})}
 async function upload(file?:File){if(!file)return;setSaving(true);try{const a=await siteContentApi.uploadSiteAsset(file,'LANDINGS');setForm(v=>({...v,hero_image_url:a.url,hero_image_drive_file_id:a.driveFileId,hero_image_mime_type:a.mimeType||'',hero_image_file_size:a.fileSize}));toast('Imagem enviada ao Google Drive.','success')}catch(e:any){toast(e.message,'error')}finally{setSaving(false)}}
 async function save(){if(!form.title.trim()||!form.headline.trim()||!form.cta_label.trim())return toast('Informe título, headline e CTA.','error');setSaving(true);try{const sections:LandingSection[]=[];const b=parse(benefits),p=parse(proof),o=parse(objections),q=parse(faq);if(b.length)sections.push({type:'benefits',title:'O que você ganha',items:b});if(p.length)sections.push({type:'proof',title:'Resultados e confiança',items:p});if(o.length)sections.push({type:'content',title:'Antes de decidir',items:o});if(q.length)sections.push({type:'faq',title:'Perguntas frequentes',items:q});sections.push({type:'cta',title:form.headline,text:finalCta||form.subheadline||'Dê o próximo passo com a Sagamente.'});await siteContentApi.saveLandingPage({...form,id:editing||undefined,campaign_id:form.campaign_id||null,sections,published_at:form.status==='published'?new Date().toISOString():null});toast('Landing salva.','success');reset();await load()}catch(e:any){toast(e.message,'error')}finally{setSaving(false)}}
 async function newCampaign(){const name=prompt('Nome da campanha');if(!name)return;try{await siteContentApi.saveCampaign({name,status:'draft'});await load();toast('Campanha criada.','success')}catch(e:any){toast(e.message,'error')}}
 return <div className="max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-3 mb-6"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#A65A2A] font-bold">Conversão</p><h1 className="text-2xl font-bold mt-1">Landing Pages & Campanhas</h1><p className="text-sm text-gray-500 mt-1">Uma oferta, um objetivo e um CTA principal. Estrutura otimizada para campanhas.</p></div><Button variant="secondary" onClick={newCampaign}>+ Campanha</Button></div>
  <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-6">
   <section className="pm-surface p-5 space-y-5"><div className="rounded-xl border border-[#A65A2A]/20 bg-[#A65A2A]/5 p-4"><p className="text-xs font-bold text-[#ff6573]">Estrutura de conversão</p><p className="text-xs text-gray-400 mt-1">Hero com proposta clara → benefícios → prova real → objeções → FAQ → CTA final. Evite links e mensagens que desviem do objetivo principal.</p></div>
    <div><h2 className="font-bold">{editing?'Editar landing':'Nova landing'}</h2><p className="text-xs text-gray-500 mt-1">O visitante deve entender a oferta e a próxima ação em poucos segundos.</p></div>
    <div className="grid sm:grid-cols-2 gap-3"><Input label="Título interno" value={form.title} onChange={set('title')}/><Input label="Slug" value={form.slug} onChange={set('slug')} placeholder="campanha-2026"/></div><Input label="Eyebrow / contexto" value={form.eyebrow} onChange={set('eyebrow')} placeholder="Design · Oferta especial"/><Input label="Headline — promessa principal" value={form.headline} onChange={set('headline')} placeholder="Resultado claro que a pessoa deseja"/><Input label="Subheadline — explique como/para quem" value={form.subheadline} onChange={set('subheadline')}/>
    <div className="grid sm:grid-cols-2 gap-3"><Input label="CTA principal — ação + benefício" value={form.cta_label} onChange={set('cta_label')}/><Input label="Destino CTA" value={form.cta_href} onChange={set('cta_href')}/></div>
    <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs text-gray-400">Campanha<select value={form.campaign_id} onChange={set('campaign_id')} className="pm-control mt-1.5 w-full px-3"><option value="">Sem campanha</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs text-gray-400">Status<select value={form.status} onChange={set('status')} className="pm-control mt-1.5 w-full px-3"><option value="draft">Rascunho</option><option value="published">Publicada</option><option value="paused">Pausada</option></select></label></div>
    {([['Benefícios','benefício | resultado para o cliente',benefits,setBenefits,4],['Prova social / confiança','prova real | detalhe, número ou contexto',proof,setProof,3],['Objeções','dúvida ou barreira | resposta objetiva',objections,setObjections,3],['FAQ','pergunta | resposta',faq,setFaq,4]] as const).map(([label,hint,value,setValue,rows])=><label key={label} className="block text-xs text-gray-400">{label} <span className="text-gray-600">— {hint}</span><textarea rows={rows} value={value} onChange={e=>setValue(e.target.value)} className="mt-1.5 w-full rounded-xl bg-white/[.05] border border-white/10 p-3 text-sm"/></label>)}
    <label className="block text-xs text-gray-400">Fechamento / CTA final<textarea rows={2} value={finalCta} onChange={e=>setFinalCta(e.target.value)} className="mt-1.5 w-full rounded-xl bg-white/[.05] border border-white/10 p-3 text-sm" placeholder="Reforce o principal benefício e reduza a última objeção."/></label>
    <div><p className="text-xs text-gray-400 mb-2">Hero visual · Google Drive</p>{form.hero_image_url&&<img src={form.hero_image_url} alt="" className="w-full max-h-72 object-cover rounded-xl mb-2"/>}<label className="inline-flex min-h-11 px-4 items-center rounded-xl bg-white/[.06] border border-white/10 text-sm cursor-pointer">Enviar imagem<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div>
    <div className="border-t border-white/10 pt-4"><h3 className="font-semibold mb-3">SEO</h3><div className="grid sm:grid-cols-2 gap-3"><Input label="Título SEO" value={form.seo_title} onChange={set('seo_title')}/><Input label="Descrição SEO" value={form.seo_description} onChange={set('seo_description')}/></div><label className="flex items-center gap-2 text-sm mt-3"><input type="checkbox" checked={form.noindex} onChange={e=>setForm(v=>({...v,noindex:e.target.checked}))}/> Não indexar esta página</label></div>
    <div className="flex gap-2"><Button onClick={save} loading={saving}>{editing?'Salvar alterações':'Criar landing'}</Button>{editing&&<Button variant="ghost" onClick={reset}>Cancelar</Button>}</div>
   </section>
   <section><h2 className="font-bold mb-3">Landings</h2><div className="space-y-3">{pages.map(p=><div key={p.id} className="pm-surface p-4"><div className="flex gap-3 justify-between"><div><p className="font-semibold">{p.title}</p><p className="text-xs text-gray-500 mt-1">/l/{p.slug} · {p.status}</p></div><button onClick={()=>edit(p)} className="text-sm text-[#ff6b7a]">Editar</button></div><div className="flex gap-2 mt-3">{p.status==='published'&&<a href={'/l/'+p.slug} target="_blank" rel="noreferrer" className="text-xs text-gray-300 underline">Abrir landing ↗</a>}</div></div>)}{!pages.length&&<p className="text-sm text-gray-500">Nenhuma landing criada.</p>}</div></section>
  </div>
 </div>
}