import { useEffect,useState } from 'react'
import { Button } from '../../components/ui/Button'
import { Input } from '../../components/ui/Input'
import { useToast } from '../../contexts/ToastContext'
import { siteContentApi,type SiteCampaign,type SiteLandingPage,type LandingSection } from '../../services/siteContent'

const blank={title:'',slug:'',headline:'',subheadline:'',eyebrow:'',cta_label:'Quero saber mais',cta_href:'/contato',secondary_cta_label:'',secondary_cta_href:'',status:'draft' as const,campaign_id:'',seo_title:'',seo_description:'',noindex:false,hero_image_url:'',hero_image_drive_file_id:'',hero_image_mime_type:'',hero_image_file_size:null as number|null}
export function AdminLandingPages(){
 const toast=useToast(),[pages,setPages]=useState<SiteLandingPage[]>([]),[campaigns,setCampaigns]=useState<SiteCampaign[]>([]),[form,setForm]=useState({...blank}),[editing,setEditing]=useState<string|null>(null),[benefits,setBenefits]=useState(''),[faq,setFaq]=useState(''),[saving,setSaving]=useState(false)
 const load=()=>Promise.all([siteContentApi.landingPages(true),siteContentApi.campaigns()]).then(([p,c])=>{setPages(p);setCampaigns(c)})
 useEffect(()=>{load().catch((e:any)=>toast(e.message,'error'))},[])
 const set=(k:keyof typeof form)=>(e:any)=>setForm(v=>({...v,[k]:e.target.value}))
 function edit(p:SiteLandingPage){setEditing(p.id);setForm({...blank,...p,campaign_id:p.campaign_id||'',subheadline:p.subheadline||'',eyebrow:p.eyebrow||'',secondary_cta_label:p.secondary_cta_label||'',secondary_cta_href:p.secondary_cta_href||'',seo_title:p.seo_title||'',seo_description:p.seo_description||'',hero_image_url:p.hero_image_url||'',hero_image_drive_file_id:p.hero_image_drive_file_id||'',hero_image_mime_type:p.hero_image_mime_type||'',hero_image_file_size:p.hero_image_file_size});const b=p.sections.find(s=>s.type==='benefits'),q=p.sections.find(s=>s.type==='faq');setBenefits((b?.items||[]).map(i=>i.title+(i.description?' | '+i.description:'')).join('\n'));setFaq((q?.items||[]).map(i=>i.title+(i.description?' | '+i.description:'')).join('\n'));window.scrollTo({top:0,behavior:'smooth'})}
 const parse=(text:string)=>text.split('\n').map(v=>v.trim()).filter(Boolean).map(v=>{const [title,...rest]=v.split('|');return {title:title.trim(),description:rest.join('|').trim()||undefined}})
 async function upload(file?:File){if(!file)return;setSaving(true);try{const a=await siteContentApi.uploadSiteAsset(file,'LANDINGS');setForm(v=>({...v,hero_image_url:a.url,hero_image_drive_file_id:a.driveFileId,hero_image_mime_type:a.mimeType||'',hero_image_file_size:a.fileSize}));toast('Imagem enviada ao Google Drive.','success')}catch(e:any){toast(e.message,'error')}finally{setSaving(false)}}
 async function save(){if(!form.title.trim()||!form.headline.trim())return toast('Informe título e headline.','error');setSaving(true);try{const sections:LandingSection[]=[];const b=parse(benefits),q=parse(faq);if(b.length)sections.push({type:'benefits',title:'Por que escolher esta solução',items:b});if(q.length)sections.push({type:'faq',title:'Perguntas frequentes',items:q});await siteContentApi.saveLandingPage({...form,id:editing||undefined,campaign_id:form.campaign_id||null,sections,published_at:form.status==='published'?new Date().toISOString():null});toast('Landing salva.','success');setForm({...blank});setEditing(null);setBenefits('');setFaq('');await load()}catch(e:any){toast(e.message,'error')}finally{setSaving(false)}}
 async function newCampaign(){const name=prompt('Nome da campanha');if(!name)return;try{await siteContentApi.saveCampaign({name,status:'draft'});await load();toast('Campanha criada.','success')}catch(e:any){toast(e.message,'error')}}
 return <div className="max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-3 mb-6"><div><h1 className="text-2xl font-bold">Landing Pages & Campanhas</h1><p className="text-sm text-gray-500 mt-1">Páginas rápidas para campanhas, com mídia no Google Drive.</p></div><Button variant="secondary" onClick={newCampaign}>+ Campanha</Button></div>
  <div className="grid lg:grid-cols-[1.1fr_.9fr] gap-6">
   <section className="p-5 rounded-2xl bg-[#141416] border border-white/10 flex flex-col gap-4"><h2 className="font-bold">{editing?'Editar landing':'Nova landing'}</h2><div className="grid sm:grid-cols-2 gap-3"><Input label="Título interno" value={form.title} onChange={set('title')}/><Input label="Slug (opcional)" value={form.slug} onChange={set('slug')} placeholder="campanha-2026"/></div><Input label="Headline" value={form.headline} onChange={set('headline')}/><Input label="Subheadline" value={form.subheadline} onChange={set('subheadline')}/><div className="grid sm:grid-cols-2 gap-3"><Input label="CTA principal" value={form.cta_label} onChange={set('cta_label')}/><Input label="Destino CTA" value={form.cta_href} onChange={set('cta_href')}/></div>
   <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs text-gray-400">Campanha<select value={form.campaign_id} onChange={set('campaign_id')} className="mt-1.5 w-full min-h-11 rounded-xl bg-white/[.05] border border-white/10 px-3"><option value="">Sem campanha</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs text-gray-400">Status<select value={form.status} onChange={set('status')} className="mt-1.5 w-full min-h-11 rounded-xl bg-white/[.05] border border-white/10 px-3"><option value="draft">Rascunho</option><option value="published">Publicada</option><option value="paused">Pausada</option></select></label></div>
   <label className="text-xs text-gray-400">Benefícios <span className="text-gray-600">— um por linha: título | descrição</span><textarea rows={5} value={benefits} onChange={e=>setBenefits(e.target.value)} className="mt-1.5 w-full rounded-xl bg-white/[.05] border border-white/10 p-3 text-sm"/></label><label className="text-xs text-gray-400">FAQ <span className="text-gray-600">— pergunta | resposta</span><textarea rows={5} value={faq} onChange={e=>setFaq(e.target.value)} className="mt-1.5 w-full rounded-xl bg-white/[.05] border border-white/10 p-3 text-sm"/></label>
   <div><p className="text-xs text-gray-400 mb-2">Imagem principal · armazenada no Google Drive</p>{form.hero_image_url&&<img src={form.hero_image_url} alt="" className="w-full h-40 object-cover rounded-xl mb-2"/>}<label className="inline-flex min-h-11 px-4 items-center rounded-xl bg-white/[.06] border border-white/10 text-sm cursor-pointer">Enviar imagem<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div>
   <div className="border-t border-white/10 pt-4"><h3 className="font-semibold mb-3">SEO da landing</h3><Input label="Título SEO" value={form.seo_title} onChange={set('seo_title')}/><div className="mt-3"><Input label="Descrição SEO" value={form.seo_description} onChange={set('seo_description')}/></div><label className="flex items-center gap-2 text-sm mt-3"><input type="checkbox" checked={form.noindex} onChange={e=>setForm(v=>({...v,noindex:e.target.checked}))}/> Não indexar esta página</label></div>
   <div className="flex gap-2"><Button onClick={save} loading={saving}>{editing?'Salvar alterações':'Criar landing'}</Button>{editing&&<Button variant="ghost" onClick={()=>{setEditing(null);setForm({...blank});setBenefits('');setFaq('')}}>Cancelar</Button>}</div></section>
   <section><h2 className="font-bold mb-3">Landings</h2><div className="space-y-3">{pages.map(p=><div key={p.id} className="p-4 rounded-2xl bg-[#141416] border border-white/10"><div className="flex gap-3 justify-between"><div><p className="font-semibold">{p.title}</p><p className="text-xs text-gray-500 mt-1">/l/{p.slug} · {p.status}</p></div><button onClick={()=>edit(p)} className="text-sm text-[#ff6b7a]">Editar</button></div>{p.status==='published'&&<a href={'/l/'+p.slug} target="_blank" rel="noreferrer" className="inline-flex mt-3 text-xs text-gray-300 underline">Abrir landing ↗</a>}</div>)}{!pages.length&&<p className="text-sm text-gray-500">Nenhuma landing criada.</p>}</div></section>
  </div>
 </div>
}
