import { useEffect,useMemo,useState } from 'react'
import { archiveCategory,createCategory,listCategories,updateCategory,type ProductCategoryRow } from '../../services/catalog'
import { useToast } from '../../contexts/ToastContext'
import { Button } from '../../components/ui/Button'

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}

export function AdminCategories(){
 const toast=useToast()
 const [rows,setRows]=useState<ProductCategoryRow[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<ProductCategoryRow|null>(null),[open,setOpen]=useState(false),[search,setSearch]=useState('')
 const [form,setForm]=useState({name:'',description:'',active:true,display_order:0})
 const load=()=>listCategories().then(setRows).finally(()=>setLoading(false))
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>rows.filter(r=>!search.trim()||[r.name,r.slug,r.description].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase()))),[rows,search])
 const active=rows.filter(r=>r.active).length
 function start(row?:ProductCategoryRow){setEditing(row||null);setForm(row?{name:row.name,description:row.description||'',active:row.active,display_order:row.display_order}:{name:'',description:'',active:true,display_order:rows.length});setOpen(true)}
 function close(){setEditing(null);setOpen(false);setForm({name:'',description:'',active:true,display_order:0})}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.name.trim())return;try{const input={...form,name:form.name.trim(),slug:slugify(form.name),description:form.description.trim()||null};if(editing)await updateCategory(editing.id,input);else await createCategory(input);toast('Categoria salva.','success');close();await load()}catch(err:any){toast(err.message,'error')}}
 async function disable(row:ProductCategoryRow){if(!confirm('Desativar a categoria "'+row.name+'"? Os itens continuam cadastrados.'))return;try{await archiveCategory(row.id);toast('Categoria desativada.','success');await load()}catch(err:any){toast(err.message,'error')}}
 return <div className="max-w-6xl">
  <div className="flex flex-wrap justify-between items-end gap-4 mb-6"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#A65A2A] font-bold">Catálogo</p><h1 className="text-2xl font-bold mt-1">Categorias</h1><p className="text-sm text-gray-500 mt-1">Organize produtos com uma estrutura simples, ordenada e fácil de manter.</p></div><Button onClick={()=>start()}>＋ Nova categoria</Button></div>
  <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-5"><div className="pm-surface p-4"><p className="text-[10px] uppercase text-gray-500">Total</p><p className="text-2xl font-bold mt-1">{rows.length}</p></div><div className="pm-surface p-4"><p className="text-[10px] uppercase text-gray-500">Ativas</p><p className="text-2xl font-bold mt-1 text-emerald-300">{active}</p></div><div className="pm-surface p-4 col-span-2 md:col-span-1"><p className="text-[10px] uppercase text-gray-500">Inativas</p><p className="text-2xl font-bold mt-1 text-gray-400">{rows.length-active}</p></div></div>
  <div className="pm-surface p-3 mb-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar categoria..." className="pm-control w-full px-4"/></div>
  {loading?<div className="py-10 text-center text-gray-500">Carregando categorias…</div>:!filtered.length?<div className="pm-surface p-8 text-center"><p className="font-semibold">Nenhuma categoria encontrada</p><p className="text-sm text-gray-500 mt-1">Crie uma categoria ou ajuste a busca.</p></div>:<div className="grid md:grid-cols-2 gap-3">{filtered.map(row=><article key={row.id} className="pm-surface p-5">
    <div className="flex justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="font-semibold truncate">{row.name}</h2><span className={'pm-tag '+(row.active?'pm-tag-success':'pm-tag-neutral')}>{row.active?'Ativa':'Inativa'}</span></div><p className="text-[10px] text-gray-600 mt-1">/{row.slug} · posição {row.display_order+1}</p></div><span className="w-9 h-9 rounded-xl bg-[#A65A2A]/10 text-[#A65A2A] flex items-center justify-center font-bold">{row.display_order+1}</span></div>
    <p className="text-sm text-gray-400 mt-4 min-h-10">{row.description||'Sem descrição.'}</p>
    <div className="flex gap-2 mt-4"><button onClick={()=>start(row)} className="min-h-10 px-3 rounded-xl bg-white/[.05] border border-white/10 text-xs">Editar</button>{row.active&&<button onClick={()=>void disable(row)} className="min-h-10 px-3 rounded-xl bg-red-500/10 text-red-300 text-xs">Desativar</button>}</div>
  </article>)}</div>}
  {open&&<div className="fixed inset-0 z-[90] bg-black/75 flex items-end sm:items-center justify-center sm:p-4" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form onSubmit={save} className="w-full max-w-xl rounded-t-2xl sm:rounded-2xl bg-[#141416] border border-white/10 p-5 space-y-4"><div className="flex justify-between"><div><p className="text-[10px] uppercase text-[#A65A2A] font-bold">Categoria</p><h2 className="text-lg font-bold">{editing?'Editar categoria':'Nova categoria'}</h2></div><button type="button" onClick={close} className="w-9 h-9 rounded-lg bg-white/5">×</button></div><label className="block text-xs text-gray-500">Nome<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="pm-control mt-1 w-full px-3"/></label><label className="block text-xs text-gray-500">Descrição<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl bg-black/30 border border-white/10 p-3"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs text-gray-500">Ordem<input type="number" min={0} value={form.display_order} onChange={e=>setForm({...form,display_order:Number(e.target.value)})} className="pm-control mt-1 w-full px-3"/></label><label className="flex items-center gap-2 text-sm pt-6"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} className="accent-[#A65A2A]"/> Categoria ativa</label></div><div className="flex gap-2 justify-end"><Button type="button" variant="secondary" onClick={close}>Cancelar</Button><Button type="submit">Salvar categoria</Button></div></form></div>}
 </div>
}