import { useEffect, useMemo, useState } from 'react'
import { academyApi } from '../../api/academy'
import { useToast } from '../../contexts/ToastContext'

const statusLabel:Record<string,string>={active:'Ativa',completed:'Concluída',cancelled:'Cancelada',inactive:'Inativo',blocked:'Bloqueado'}
export function AdminAcademyStudents(){
 const toast=useToast(); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<any|null>(null); const [showEnroll,setShowEnroll]=useState(false); const [courses,setCourses]=useState<any[]>([]); const [offerings,setOfferings]=useState<any[]>([]); const [enroll,setEnroll]=useState({course_id:'',offering_id:'',user_id:''})
 useEffect(()=>{academyApi.academicStudents().then(setRows).catch((e:any)=>toast(e.message,'error')).finally(()=>setLoading(false));academyApi.adminCourses().then(setCourses).catch(()=>{});academyApi.offerings().then(setOfferings).catch(()=>{})},[])
 const students=useMemo(()=>{const grouped=new Map<string,any>();for(const r of rows){const id=r.student?.id||r.student_id;if(!id)continue;const current=grouped.get(id)||{id,ra:r.student?.academic_record,status:r.student?.status,profile:r.user,enrollments:[]};current.enrollments.push(r);grouped.set(id,current)}return [...grouped.values()]},[rows])
 const filtered=students.filter(s=>{const name=[s.profile?.first_name,s.profile?.last_name].filter(Boolean).join(' ');return [name,s.profile?.email,s.ra].join(' ').toLowerCase().includes(query.toLowerCase())})
 const open=(s:any)=>setSelected(s)
 const createEnrollment=async()=>{if(!enroll.user_id||!enroll.offering_id)return toast('Selecione aluno e oferta.','error');try{await academyApi.academicEnroll(enroll.user_id,enroll.offering_id);toast('Matrícula acadêmica criada.','success');setShowEnroll(false);setEnroll({course_id:'',offering_id:'',user_id:''});setRows(await academyApi.academicStudents())}catch(e:any){toast(e.message,'error')}}
 if(loading)return <div className="p-6 text-sm text-gray-500">Carregando vida acadêmica...</div>
 return <div className="p-4 md:p-6 space-y-5 text-gray-100">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[.2em] text-[#E30613] font-bold">Secretaria</p><h1 className="text-2xl font-bold">Alunos acadêmicos</h1><p className="text-sm text-gray-500">RA, matrículas, matrizes, ofertas, progresso e histórico em uma visão única.</p></div><button onClick={()=>setShowEnroll(true)} className="rounded-xl bg-[#E30613] px-4 py-2.5 text-sm font-bold text-white">＋ Nova matrícula</button></div>
  <div className="grid grid-cols-3 gap-3">{[['Alunos',students.length],['Matrículas',rows.length],['Concluídas',rows.filter(r=>r.status==='completed').length]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-white/[.08] bg-white/[.025] p-4"><div className="text-xs text-gray-500">{l}</div><div className="text-2xl font-bold">{v}</div></div>)}</div>
  <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, e-mail ou RA" className="w-full rounded-xl border border-white/10 px-4 py-3 bg-white/[.025] text-gray-200 outline-none focus:border-[#E30613]" />
  <div className="grid lg:grid-cols-[360px_1fr] gap-4">
   <div className="space-y-2">{filtered.map(s=>{const name=[s.profile?.first_name,s.profile?.last_name].filter(Boolean).join(' ')||s.profile?.email||'Aluno';return <button key={s.id} onClick={()=>open(s)} className={'w-full text-left rounded-xl border border-white/[.08] p-4 bg-white/[.025] text-gray-200 '+(selected?.id===s.id?'border-[#E30613] ring-1 ring-[#E30613]':'')}><div className="font-semibold">{name}</div><div className="text-xs text-gray-500">{s.ra} · {s.enrollments.length} matrícula(s)</div></button>})}</div>
   <div className="rounded-xl border border-white/[.08] bg-white/[.025] p-5 text-gray-200">{!selected?<div className="text-sm text-gray-500">Selecione um aluno para abrir a vida acadêmica.</div>:<StudentDetail student={selected}/>}</div>
  </div>
  {showEnroll&&<div className="fixed inset-0 z-[80] bg-black/75 p-3 md:p-8 overflow-auto"><div className="mx-auto max-w-xl rounded-2xl border border-white/10 bg-[#111113] p-5 space-y-3"><div className="flex justify-between"><h3 className="text-lg font-bold">Nova matrícula</h3><button onClick={()=>setShowEnroll(false)} className="h-9 w-9 rounded-lg border border-white/10">✕</button></div><select className="w-full rounded-xl border border-white/10 bg-[#0d0d0f] p-3" value={enroll.user_id} onChange={e=>setEnroll({...enroll,user_id:e.target.value})}><option value="">Aluno / cliente</option>{rows.reduce((a:any[],r:any)=>a.some(x=>x.id===r.user?.id)?a:[...a,r.user],[]).filter(Boolean).map((u:any)=><option key={u.id} value={u.id}>{[u.first_name,u.last_name].filter(Boolean).join(' ')||u.email}</option>)}</select><select className="w-full rounded-xl border border-white/10 bg-[#0d0d0f] p-3" value={enroll.course_id} onChange={e=>setEnroll({...enroll,course_id:e.target.value,offering_id:''})}><option value="">Curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select className="w-full rounded-xl border border-white/10 bg-[#0d0d0f] p-3" value={enroll.offering_id} onChange={e=>setEnroll({...enroll,offering_id:e.target.value})}><option value="">Oferta / turma</option>{offerings.filter(o=>!enroll.course_id||o.course_id===enroll.course_id).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><button onClick={createEnrollment} className="w-full rounded-xl bg-[#E30613] px-4 py-3 text-sm font-bold">Efetivar matrícula</button></div></div>}
 </div>
}
function StudentDetail({student}:any){
 const toast=useToast(); const [record,setRecord]=useState<any>(null); const [busy,setBusy]=useState<string|null>(null); const [tab,setTab]=useState<'overview'|'enrollments'|'grades'|'history'|'documents'|'certificates'>('overview')
 const openRecord=async(e:any)=>{setBusy(e.id);try{await academyApi.refreshEnrollment(e.id);setRecord({enrollment:e,...await academyApi.academicRecord(e.id,student.profile?.id,e.course?.id)});}catch(x:any){toast(x.message,'error')}finally{setBusy(null)}}
 const name=[student.profile?.first_name,student.profile?.last_name].filter(Boolean).join(' ')||student.profile?.email||'Aluno'
 return <div className="space-y-5"><div><div className="text-[10px] uppercase tracking-[.18em] text-[#E30613] font-bold">Ficha acadêmica</div><h2 className="text-xl font-bold">{name}</h2><div className="text-sm text-gray-500">{student.profile?.email}</div><div className="mt-2 flex flex-wrap gap-2"><span className="inline-flex rounded-full bg-white/[.06] px-3 py-1 text-xs font-semibold">{student.ra}</span><span className="inline-flex rounded-full bg-white/[.04] px-3 py-1 text-xs text-gray-400">{statusLabel[student.status]||student.status||'Ativo'}</span></div></div>
 <div className="flex gap-2 overflow-x-auto pb-1">{([['overview','Visão geral'],['enrollments','Matrículas'],['grades','Notas'],['history','Histórico'],['documents','Documentos'],['certificates','Certificados']] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={'whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold border '+(tab===id?'bg-[#E30613] border-[#E30613] text-white':'border-white/10 text-gray-400')}>{label}</button>)}</div>
 {tab==='overview'&&<div className="grid sm:grid-cols-3 gap-2">{[['Matrículas',student.enrollments.length],['Concluídas',student.enrollments.filter((e:any)=>e.status==='completed').length],['Em andamento',student.enrollments.filter((e:any)=>e.status==='active').length]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-black/20 border border-white/[.06] p-3"><div className="text-[10px] uppercase text-gray-600">{l}</div><div className="text-xl font-bold mt-1">{v}</div></div>)}</div>}
 {tab==='documents'&&<div className="rounded-xl border border-dashed border-white/10 p-5"><div className="text-sm font-semibold">Documentos acadêmicos</div><p className="text-xs text-gray-500 mt-1">Área preparada para o motor documental do PR #194. Nenhum documento paralelo será criado nesta etapa.</p></div>}
 <div className="space-y-3">{student.enrollments.filter((e:any)=>tab==='certificates'?e.status==='completed':true).map((e:any)=><div key={e.id} className={'rounded-xl border border-white/[.08] bg-black/20 p-4 '+(tab==='documents'?'hidden':'')} ><div className="flex flex-wrap justify-between gap-2"><div><div className="font-semibold">{e.course?.title}</div><div className="text-xs text-gray-500">{e.enrollment_number}</div></div><span className="text-xs font-semibold">{statusLabel[e.status]||e.status}</span></div>{tab!=='history'&&<div className="mt-3 grid sm:grid-cols-2 gap-2 text-sm"><div><b>Matriz:</b> {e.curriculum?.name||'—'}</div><div><b>Oferta:</b> {e.offering?.name||'—'}</div><div><b>Progresso:</b> {e.progress_percent??0}%</div><div><b>Nota final:</b> {e.final_grade??'—'}</div><div><b>Frequência:</b> {e.attendance_percent!=null?e.attendance_percent+'%':'—'}</div><div><b>Origem:</b> {e.origin||e.source||'—'}</div></div>}{tab!=='history'&&<button onClick={()=>openRecord(e)} className="mt-4 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-gray-300 hover:border-[#E30613]">{busy===e.id?'Atualizando...':tab==='grades'?'Abrir notas e resultados':tab==='certificates'?'Abrir registro e certificado':'Boletim e histórico'}</button>}{(tab==='history'||tab==='overview')&&e.events?.length?<div className="mt-4 border-t border-white/[.08] pt-3"><div className="text-xs font-bold uppercase text-gray-500 mb-2">Histórico</div>{e.events.map((ev:any)=><div key={ev.id} className="text-sm py-1">{ev.title} <span className="text-xs text-gray-400">· {new Date(ev.occurred_at).toLocaleDateString('pt-BR')}</span></div>)}</div>:null}</div>)}</div>{record&&<AcademicRecord data={record} onClose={()=>setRecord(null)}/>}</div>
}
function AcademicRecord({data,onClose}:any){const p=new Map<string,any>(data.progress.map((x:any)=>[x.lesson_id,x]));const best=(id:string)=>Math.max(-1,...data.attempts.filter((x:any)=>x.assessment_id===id).map((x:any)=>Number(x.score)));return <div className="fixed inset-0 z-[80] bg-black/70 p-3 md:p-8 overflow-auto"><div className="mx-auto max-w-4xl rounded-2xl border border-white/10 bg-[#111113] p-5 text-gray-200 shadow-2xl"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase text-[#E30613]">Registro acadêmico</div><h3 className="text-xl font-bold">{data.enrollment.course?.title}</h3><div className="text-xs text-gray-500">{data.enrollment.enrollment_number}</div></div><button onClick={onClose} className="h-9 w-9 rounded-lg border border-white/10">✕</button></div><div className="mt-5 grid sm:grid-cols-3 gap-2">{[['Progresso',(data.enrollment.progress_percent??0)+'%'],['Nota final',data.enrollment.final_grade??'—'],['Certificado',data.certificate?'Emitido':'—']].map(([a,b])=><div className="rounded-xl bg-white/[.04] p-3" key={a}><div className="text-xs text-gray-500">{a}</div><b>{b}</b></div>)}</div><div className="mt-5 space-y-4">{data.modules.map((m:any)=><div key={m.id}><h4 className="text-sm font-bold">{m.title}</h4><div className="mt-2 space-y-1">{(m.course_lessons||[]).filter((l:any)=>l.status==='published').map((l:any)=><div key={l.id} className="flex justify-between rounded-lg bg-black/20 px-3 py-2 text-xs"><span>{l.title}</span><span>{p.get(l.id)?.completed?'Concluída':'Pendente'}</span></div>)}{data.assessments.filter((a:any)=>a.module_id===m.id).map((a:any)=>{const s=best(a.id);return <div key={a.id} className="flex justify-between rounded-lg border border-white/[.06] px-3 py-2 text-xs"><span>{a.kind==='evaluation'?'Avaliação':'Atividade'} · {a.title}</span><span>{s<0?'Sem tentativa':s+'% · '+(s>=a.passing_percent?'Aprovado':'Pendente')}</span></div>})}</div></div>)}</div>{data.certificate&&<a href={'/certificados/'+data.certificate.verification_code} className="mt-5 inline-flex rounded-xl bg-[#E30613] px-4 py-2 text-sm font-bold text-white">Abrir certificado</a>}</div></div>}
